### ISSUE TITLE
[A13] Themed icon is gone after rebrand

### ISSUE THREAD

**Issue by KibSquib48** [sk22/megalodon#101]
Before:
![Screenshot_20221119-185745~2](https://user-images.githubusercontent.com/33189136/203868890-8293235e-a7de-425e-825e-cd433e808dae.png)

After:
![Screenshot_20221124-170551](https://user-images.githubusercontent.com/33189136/203868898-31a56e7a-2b3c-4fcd-b5f4-aa0f1985632e.png)

It seems like making a monochrome icon out of the new one would be simple but I don't have anything I could use to make a mockup at the moment

**Comment by sk22** [comment]
really good to know that it doesn't work, thanks! i actually did include a monochrome icon, but it probably messed up the configuration for the adaptive icon… i'll see what i can do!

**Comment by sk22** [comment]
besides, i actually struggled making a monochrome icon i was happy with – so if anyone has any suggestions for improvement, feel free to let me know!!

**Comment by sk22** [comment]
okay, should be fixed in the new version! can you let me know if it works and share another screenshot? couldn't really test it myself :')

**Comment by sk22** [comment]
really interested to see if it looks good or now; i've seen that i can also turn down the opacity for paths inside the monochrome icon. might to that for the shark's back, and omit the border altogether

**Comment by KibSquib48** [comment]
looks great to me!
![Screenshot_20221125-153246](https://user-images.githubusercontent.com/33189136/204052913-449b8a56-14c2-4af3-a05d-3f2ab99e663f.png)

**Comment by sk22** [comment]
ah amazing, thanks for the screenshot!
