### ISSUE TITLE
[Bug] Cannot add alt-text to already uploaded images while editing a post

### ISSUE THREAD

**Issue by andreadistefano** [sk22/megalodon#104]
Hi again, in relation to issue #103, I posted some pictures without alt-text.  
When I learned about this useful feature, I tried to edit my post to add a description to the images I already posted, but the app wouldn't let me.  
The only way to do this is to delete the pictures from the post and add them again with alt-text.  

Steps to reproduce:
1. create a post with some pictures without alt-text
2. edit the post
3. add alt-text to the pictures
4. when saving, the app shows an error message "Record not found"

**Comment by sk22** [comment]
that's an upstream issue: mastodon#327
i hope it's fixed there soon, else i might try to do it
