### ISSUE TITLE
Monochrome icon tweaks

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#105]
* [ ] Make notification icon border a little bit wider
* [x] Figure out why the monochrome/themed adaptive icon doesn't work

**Comment by LucasGGamerM** [comment]
Can you please add a manual toggle for the monochrome icon?

**Comment by sk22** [comment]
> Can you please add a manual toggle for the monochrome icon?

you mean the one that's only rendered in android 13, when themed adaptive icons are turned on? well… no, i wouldn't know how and i don't intend bloating the settings page too much

**Comment by sk22** [comment]
i don't think i will ever do that, lol
