### ISSUE TITLE
[feature request] Push notification using UnifiedPush

### ISSUE THREAD

**Issue by Surendrajat** [sk22/megalodon#108]
Details: https://unifiedpush.org/developers/android/

See [Tusky's implemetation](https://github.com/tuskyapp/Tusky/pull/2303) of it.

**Comment by LucasGGamerM** [comment]
I'm working on this

**Comment by JohnySeven** [comment]
Just little note here, Tusky app is very slow with delivering push notifications. I was comparing Megalodon and Tusky running on one device with same account and Megalodon current implementation was about 5-15 minutes faster than Tusky.

**Comment by PoorPocketsMcNewHold** [comment]
> Just little note here, Tusky app is very slow with delivering push notifications. I was comparing Megalodon and Tusky running on one device with same account and Megalodon current implementation was about 5-15 minutes faster than Tusky.

That is, if you even got FCM integration. In that case, Megalodon doesn't even make notifications at all.

**Comment by sk22** [comment]
megalodon has exactly the same push notification implementation as the "official" mastodon app, and as such does support FCM

**Comment by PoorPocketsMcNewHold** [comment]
> megalodon has exactly the same push notification implementation as the "official" mastodon app, and as such does support FCM

I meant, if you got Google services on your phone to make it work. _To be fair, it's a bit of a minority, but it'e for the sake of being fully FLOSS_.

**Comment by marc0x1** [comment]
Any update?

**Comment by LucasGGamerM** [comment]
Actually yes, I have found a way to subscribe to up-fcm, and I am working on implementing it on the app. I have no ETAs though, as school has taken up a majority of my time lately

**Comment by kevino-techie** [comment]
excited for this since with conversations. im now also acts as a unified push distributor , so i don't need another app to install. Also it seems to be quite fast with other apps.

**Comment by pabloscloud** [comment]
> > megalodon has exactly the same push notification implementation as the "official" mastodon app, and as such does support FCM
> 
> I meant, if you got Google services on your phone to make it work. _To be fair, it's a bit of a minority, but it'e for the sake of being fully FLOSS_.

Exactly, I am on calyxOS and I don't receive any notifications anymore for some reason. I now switched to Tusky instead cause they stopped working

**Comment by sk22** [comment]
replying to @kaisercalm (#563):

> It's kind of a shame that something like UnifiedPush exists, but most app developers aren't keen on supporting it, which would honestly be the only way UnifiedPush could get popular. I get why, because the userbase for it isn't that big and most people _definitely_ aren't completely degoogled, but damn would it be nice if more apps did use it.

i agree, it is - it's just that it's not the biggest priority for me personally, which is why i haven't looked into it yet. though, i have thought about looking what's missing to get listed on f-droid in the "near" future, and i think that unifiedpush support would definitely be something that would also be beneficial for the f-droid listing.

related: https://github.com/LucasGGamerM/moshidon/issues/206#issuecomment-1572826832
