### ISSUE TITLE
Failed to resolve: me.grishka.appkit:appkit:1.2.7

### ISSUE THREAD

**Issue by LucasGGamerM** [sk22/megalodon#112]
I am trying to compile megalodon from source to make some changes to the colors, but the Gradle fails to sync due to failing to resolve such library. Trying to manually setting it to version 1.2.6 and building results in another error in mastodon/java/org.joinmastodon.android/fragments/discover/SearchFragment.java in line 179:

```	
imgLoader.forceUpdateImages();
		         ^
  symbol:   method forceUpdateImages()
  location: variable imgLoader of type ListImageLoaderWrapper
```

**Comment by Surendrajat** [comment]
According to [this comment](https://github.com/mastodon/mastodon-android/issues/19#issuecomment-1099835315) latest appkit won't be uploaded to maven repo for a while so you will have to build it locally.
I got it working this way:
- `git clone https://github.com/grishka/appkit.git`
- Open `appkit/maven-push.gradle` file and comment out these line from the end:
 ```groovy
    signing {
        sign publishing.publications.release
    }
```
- Run `./gradlew publishToMavenLocal`

You should be able to build the app properly after that.

**Comment by LucasGGamerM** [comment]
Thank you, it worked. I shall close this issue.
