### ISSUE TITLE
In a poll, mark the entry you've voted for

### ISSUE THREAD

**Issue by lyfja** [sk22/megalodon#113]
Currently, there is no check mark or any other kind of indication to display what you've voted for in a poll.

**Comment by neilideal** [comment]
Totally agree! It would also be nice to be able to change your answer in the voting.

**Comment by sk22** [comment]
actually, when a poll supports voting for multiple options, there's a dedicated "vote" button you can press after selecting one (or more) of the options. i think i'll just enable this for all polls!
and regarding the indication; i think nothing speaks against displaying the (ticked) checkboxes after voting :)

**Comment by neilideal** [comment]
> actually, when a poll supports voting for multiple options, there's a dedicated "vote" button you can press after selecting one (or more) of the options. i think i'll just enable this for all polls!
> and regarding the indication; i think nothing speaks against displaying the (ticked) checkboxes after voting :)

I was talking in general about an unvote button, like in telegram, for example
