### ISSUE TITLE
Access to Announcements

### ISSUE THREAD

**Issue by Ghryphen** [sk22/megalodon#127]
Would like the ability to see server Announcements and the server About page.

Our server makes regular use of the server Announcements however there is no display for them.

Would also like access to the server About page as it contains links to resources and info.

Rough mock-up for announcements with unread notification dot.

![markup_1000000896~3](https://user-images.githubusercontent.com/128811/205468819-c9ebdd26-6f62-46d3-855d-fa16caa8f6d5.png)

**Comment by HerrHulaHoop** [comment]
This is a nice addition. Would be nice if we can have this integrated into the notifications section. Don't see much point to having as a button in the timeline when we have a dedicated section for notifications.

I'm aware that this is how it is shown on the web interface but just dropping my two cents here.

**Comment by sk22** [comment]
I probably won't include the server about page (for now), but I definitely should add at least a link to it in the settings. I have, however, just implemented announcements and am hereby closing this issue! (Will be shipped in the next release)
