### ISSUE TITLE
Language selector is missing toki pona

### ISSUE THREAD

**Issue by emmatebibyte** [sk22/megalodon#139]
**Describe the bug**
toki pona is missing from the language selector.

**To Reproduce**
1. Click the post creation icon
2. Open the language selector
3. Scroll through it
4. tfw no toki pona

**Version**
Megalodon version: v.1.1.4+fork.58

**Comment by sk22** [comment]
okay, seems like the language list android is giving me is also missing some languages in addition to displaying some that mastodon doesn't support. will have to look into it, thanks for letting me know!

**Comment by sk22** [comment]
looks like i'll need to hard-code these languages… https://github.com/mastodon/mastodon/blob/main/app/helpers/languages_helper.rb
