### ISSUE TITLE
Creating account through the app doesn't not work, and results in a locale missing error toast 

### ISSUE THREAD

**Issue by LucasGGamerM** [sk22/megalodon#142]
Cannot create account through any official android mastodon Fork.

**Comment by sk22** [comment]
does "through any official android mastodon fork" include the upstream app too? if so, is there an upstream bug report?
(tbh, i don't really want to look into this; registration through the app seems broken anyway – has locked me out of the app more than once 😅)

**Comment by LucasGGamerM** [comment]
It's a bug on upstream. I think I should bug report there too

**Comment by sk22** [comment]
closing since the signup procedure is now inaccessible through megalodon
