### ISSUE TITLE
Tapping on a post from the timeline crashes the app

### ISSUE THREAD

**Issue by LionsSharks15** [sk22/megalodon#143]
I just updated to v1.1.4+fork.58 and if I tap on a post on my timeline to view replies, the app crashes. This does not happen if I tap on a notification that links back to my own post though.

**Comment by LionsSharks15** [comment]
This does not happen on the official app. It occurs with every post I click on the timeline.
Btw, last night I ran a bug report thing through android, is there anything I can useful to you that i can send from that?

**Comment by grungefox** [comment]
I have similar issue, but only with posts from non-Mastodon servers (Pleroma/Misskey/Calckey), otherwise everything works just fine. I still can comment, boost and fav those posts, but when I click on them, to see the comments or pictures, Megalodon simply crashes.

It also doesn't occur on the official Mastodon app, nor does it on the previous Megalodon version.

Reinstalling it or clearing the app's data fixes this problem only temporarly, until I open it for the 2nd time.

**Comment by sk22** [comment]
i haven't had this issue myself. can someone maybe link me to a post where this occurs?

**Comment by grungefox** [comment]
I don't want to share anyone's post, so here's my own note from Calckey:
https://i.calckey.cloud/notes/98anuyt6zj

Even when I pasted it to the search field and then clicked on it, Megalodon crashed

Maybe it has something to do with feature that is supported by Mastodon, but not by Misskey/Calckey?

**Comment by LionsSharks15** [comment]
That's weird. Im trying it out again on my phone and it is only happening for certain posts.
Some instances it crashed on:
trans.enby.town
milker.cafe
udongein.xyz
social.beepboop.ga
These are just some instances.

**Comment by sk22** [comment]
> I don't want to share anyone's post, so here's my own note from Calckey: https://i.calckey.cloud/notes/98anuyt6zj
> 
> Even when I pasted it to the search field and then clicked on it, Megalodon crashed
> 
> Maybe it has something to do with feature that is supported by Mastodon, but not by Misskey/Calckey?

weird, i can open it just fine!?
does it also occur for you on the latest version?

if yes: can you somehow provide a crash log?
because idk, i can't replicate it, so i can't really do anything about it at the moment…

**Comment by grungefox** [comment]
Yes, it seems like it doesn't work on version 59 either. What do I need to do to get a crash log?

**Comment by sk22** [comment]
ahh!! wait, i can replicate it!! it seems to only occur through vanilla mastodon servers though? i apparently couldn't replicate it because i'm normally logged in to a glitch-soc server
will look into it asap!

**Comment by LionsSharks15** [comment]
I hate to reopen a closed issue, but I just clicked on a post from @traabot@ihatebeinga.live and it crashes megalodon every time.
I am commenting on this closed issue because its still the same issue.

**Comment by sk22** [comment]
the fix isn't released yet!

**Comment by LionsSharks15** [comment]
Oh sorry! I had recently updated the app through f-droid so I assumed that was the bug fix update.
