### ISSUE TITLE
Posts still say “via Mastodos”

### ISSUE THREAD

**Issue by emmatebibyte** [sk22/megalodon#145]
**Describe the bug**
When I make a post, it says I'm using Mastodos.

**To Reproduce**
1. Create a post.
2. Look at the “via [client]” text
3. See that it says “via Mastodos”
4. mfw

**Screenshots and screen recordings**
![Screenshot_20221211-102600_Megalodon](https://user-images.githubusercontent.com/58507086/206912495-a9e76039-0027-44bb-a6a4-c004e13c6026.png)

**Version**
Megalodon version: v1.1.4+fork.58

**Comment by AverageDood** [comment]
Logout and relogin, and you should be good to go

**Comment by sk22** [comment]
see #128. again, idk if there's anything i can do about that nor if it's worth the effort. (maybe by updating the token maybe? i haven't touched the auth code and tbh i don't plan to. if someone wants to look into it, please do!)

**Comment by emmatebibyte** [comment]
thank you :)
