### ISSUE TITLE
[ Bug ] Reply, fav, and boost count doesn't work.

### ISSUE THREAD

**Issue by nitrogenez** [sk22/megalodon#147]
**Describe the bug**
Recently I've opened issue about feature for showing counts near icons, but I didn't know that is a bug.

**To Reproduce**
Unknown. Didn't change anything, didn't even know about that, just installed latest v1.1.4+fork.58.

**Screenshots and screen recordings**
![Screenshot_2022-12-12-15-57-18-18_97294d061ac208a4e8e283a3feb896c9](https://user-images.githubusercontent.com/112193680/207064245-17335308-c82e-4df5-82cd-9b805f721bff.jpg)

![Screenshot_2022-12-12-15-57-36-82_97294d061ac208a4e8e283a3feb896c9](https://user-images.githubusercontent.com/112193680/207064277-a17fb1fa-9509-4a09-9ade-a68b350d3d69.jpg)

**Version**
Megalodon version: v1.1.4+fork.58

**Additional context**
- Does this issue also occur with the respective upstream release? Yes.

**Crash log**
No crash appeared.

**Comment by sk22** [comment]
have you… enabled the “show interaction counts” toggle in the settings and then tried refreshing the timeline?

**Comment by sk22** [comment]
closing again because i'm pretty sure you just didn't enable the right setting (i don't see that in your screenshots). let me know if it keeps not working!
