### ISSUE TITLE
Text is cut off

### ISSUE THREAD

**Issue by muznyo** [sk22/megalodon#157]
**Describe the bug**
Posts and following text is cut off

**To Reproduce**
1. Go to any profile
2. You will see that text is cut off

**Screenshots and screen recordings**
![Screenshot_20221217-113710_Megalodon_edited_1671273638239341.png](https://user-images.githubusercontent.com/24987471/208237866-a9a94400-6629-47aa-a2b6-2ea9b3b37e7e.png)

**Version**
Megalodon version: 
v1.1.4+fork.59

**Comment by sk22** [comment]
please let me know whether the issue still persists in the next release - i can't reproduce it because it doens't happen with my font.

**Comment by muznyo** [comment]
It is fixed now in latest version!
