### ISSUE TITLE
Filters being Ignored in Megalodon

### ISSUE THREAD

**Issue by bama35453** [sk22/megalodon#161]
**Describe the bug**
The filters defined on the Mastodon page (Settings / Filters / Add new filter) are currently being ignored by the Megalodon app.

**To Reproduce**
To reproduce go to the Mastodon page and create a filter based on a word / hashtag appearing often in your local / federated timeline (ideally tick the checkbox to hide them with a warning). After some time compare the posts on the Mastodon page and in Megalodon. Scroll on the web page until you see an entry "Filtered: "yourdefinedword". Now scroll to the same post in Megalodon. There the filtered item will show up even though it should be hidden.

Expected behavior: In Megalodon the posts before and behind the filtered item should be displayed but not the filtered item itself. This should apply to the home timeline, the local timeline and the federated timeline.

**Version**
Megalodon version: v1.1.5+fork.61-play

**Additional context**
Probably this part of Megalodon is based on the Mastodon app version 1.1.3? This version of the Mastodon app showed exactly the same behavior. Filters work correctly since the latest Mastodon version 1.1.4 only.

**Comment by bama35453** [comment]
I just realized the filters in official Mastodon app not being reliable at all.
Sometimes it doesn't recognize the filter criteria. It seems to be depending on the position of the respective string within a post.
So I have to correct my statement. In the official it works just partially.

**Comment by sk22** [comment]
There's a relatively long discussion under in this (closed) upstream issue: https://github.com/mastodon/mastodon-android/issues/94

Might actually try to just do it myself, too many people have told me that filters don't work properly… 😅
