### ISSUE TITLE
Followed hashtags

### ISSUE THREAD

**Issue by leachimus** [sk22/megalodon#162]
Please include an option of followed hashtags.

**Comment by sk22** [comment]
As far as I know, there's no way apps (including Mastodon on the web) can get a list of followed hashtags anywhere, so there's nothing I can do about this. If you see the feature elsewhere, please let me know!

**Comment by leachimus** [comment]
Hello and thank you for the answer. The app Fedilab can do that. Have a look at it there. But I find your fork more pleasant and do not want to change.

**Comment by sk22** [comment]
oh, good to know, thanks!

**Comment by sk22** [comment]
will look into how this is implemented!
