### ISSUE TITLE
Option to disable swiping between tabs

### ISSUE THREAD

**Issue by Brawaru** [sk22/megalodon#165]
**Is your feature request related to a problem? Please describe.**

When scrolling explore tab I often find myself switching to other tab by accidentally swiping to the side instead of scrolling up or down, completely unintentionally, because depending on small initial motion app decides whether it's going to move between tabs or scroll, and then you don't even move your finger that much, yet it detects motion (points given though, it's still less sensitive than what Tusky had before they disabled swiping by default) and decides to change the tab. But then you also sometimes want to scroll feed very quickly to go through many many posts, like federated feed, and that's when this issue just shines, unless you are a robot, I think you'll switch tab a few times yourself.

**Describe the solution you'd like**

Having an option like in Tusky (maybe also disabled by default) where it turns off tab swiping would be great.

**Describe alternatives you've considered**

- Try to fix my fat fingers / phone screen relationship to not be so erratic that they miscommunicate less and don't do something I don't want. I actually tried that but had a bad luck. So unfortunate 💔 
- Ignoring this completely and just swiping tab back every time this happens. That's what I do now, but it's incredibly annoying! At least scroll position does not reset... that's something.

**Additional context**

Please consider this picture of an elephant:
![Picture of a baby elephant strolling through a bunch of grass](https://user-images.githubusercontent.com/10401817/208307753-c0baa165-ba93-4c52-b1e3-d33168c77c7e.jpg)
*[Photo](https://unsplash.com/photos/OxsU3hHvG90) by [David Clode](https://unsplash.com/@davidclode) on [Unsplash](https://unsplash.com/)*

Thank you so much for this great fork!

**Comment by sk22** [comment]
elephant considered, thanks!
