### ISSUE TITLE
Ability to translate posts

### ISSUE THREAD

**Issue by coderkei** [sk22/megalodon#171]
**Is your feature request related to a problem? Please describe.**
I have recently started using the Fediverse like many people and this is possibly the best client to use currently, however one feature I miss is the translate post button. This was a feature twitter had for translating other users posts into your native language by pressing a button on the tweet.

**Describe the solution you'd like**
Please would it be possible to add such a button for posts to translate them, using a backend that allows for it (such as DeepL or LibreTranslate etc).

**Describe alternatives you've considered**
The only alternative I have found is copying & pasting the post text into a translation app to read it.

I hope you will consider this as it will improve the experience for me, thank you.

**Comment by sk22** [comment]
[Already implemented](https://github.com/mastodon/mastodon-android/compare/master...sk22:megalodon:feature/translate-button) - keep in mind that it only works if your server supports it.

**Comment by coderkei** [comment]
@sk22 Ah I see its a server-side feature. Would any client-side support be added in the future? The instance I use doesn't support it, and not all users I follow are on the same instance either.

Its not super important but it would better than having to copy & paste text of some users I follow into Google Translate 😅

**Comment by sk22** [comment]
no, as this would require me automatically pushing users' content through proprietary translation services without their consent - plus it'd be way too much effort for me.
you could install some translator app, select the text and directly share it into the app, maybe that's quicker than copy-pasting it!

**Comment by coderkei** [comment]
@sk22 I didn't consider that it would put users posts through a proprietary service oops!

In that case I will see if I can find a translator app that can do as you suggested ^^

**Comment by sk22** [comment]
google translator can, maybe DeepL can too :)
