### ISSUE TITLE
Special treatment for links pointing to same instance & navigate them natively

### ISSUE THREAD

**Issue by thekalinga** [sk22/megalodon#177]
**Is your feature request related to a problem? Please describe.**

If I am on an instance x.com & I make a post with a link pointing to a link within the same instance — say http[s]://x.com/…  (or) x.com/…, when I click on this link, application currently opens it in browser just like any external link. It breaks the native app flow as user is moved out of application.

**Describe the solution you'd like**

If a link points to self-instance, instead of opening those links in a browser, since all these posts are within same mastondon instance, the app should show these linked post(s) as embedded posts (like quote tweet) by making additional queries to server for these links. Tapping on the embedded tweet should directly take the user to the tapped post in question natively without opening browser (just like how we navigate in home feed). Back press should navigate user back to previous screen just like in home screen.

**Describe alternatives you've considered**

Alternative for handling same-instance links is to not make additional queries when rendering embedded posts (like in case of quote tweets) as its slightly more effort & adds slight load on server (I dont think server load such a big deal but nevertheless its a cost we need to consider), tap handler for links pointing to same-instance can be modified such that when user taps on the post (same-instance links), he should be taken to the post within the application natively like we have in home screen without opening any browser.

**Comment by sk22** [comment]
uh, the app already opens links from your home instance in the app - at least when the links aren't in bio or profile metadata but in actual posts, for whatever reason. i "plan" (i don't really *plan* to do anything, i'd just like to have it implemented and will probably try some time) to support in-app navigation for all fedi links, as per #96, in which case this issue would be a duplicate. unless i misunderstood something?

**Comment by thekalinga** [comment]
Thanks for linking to other issue. If thats implemented, a majority of what I mentioned here would be solved.

Altho previewing of mastodon posts linked (not showing complete post content from linked post, but just 1st few 100 chars or so) is quite useful so that people will have rough context. I think this aspect is not covered there. If this is also considered as part of that issue/another issue, users will have much smoother experience.
