### ISSUE TITLE
Use Material You switches 

### ISSUE THREAD

**Issue by Mattis142** [sk22/megalodon#184]
The app currently uses pretty outdated looking original material design switches
I'd recommend using newer Material you switches for a more modern feel in the settings
https://m3.material.io/components/switch/overview

I think this would work great with some additional material you upgrades in the future as well

**Comment by neilideal** [comment]
It feels like this issue might be closed because of the transfer to Material you

**Comment by sk22** [comment]
oh i will close it, no worries :D right now, in dev, the material 3 switches still look streteched for some reason.. so i'm keeping this open for now
