### ISSUE TITLE
Alternativ icon color - purple instead of pink

### ISSUE THREAD

**Issue by BluePixel4k** [sk22/megalodon#186]
I'm fine with the pink color of the icon. But I think the app would get a lot more attention if the color of the icon covered more tastes.

I think the purple of the official Mastodon logo would match well with the Megalodon shark.
As an example:
<img src="https://user-images.githubusercontent.com/77979781/209292361-d160649b-e6c8-4696-801b-e5ccf5ae7887.png" width="150" /> <img src="https://user-images.githubusercontent.com/77979781/209292375-5d8dc02b-51e5-4a68-bce3-6c595f2f9ae8.png" width="150" />
The second advantage of purple would be that new users would see a relation to Mastodon faster.

Maybe you can make the pink icon optional in the settings.

I would love it, if you could think it through. 
Thx. 😊

**Comment by sk22** [comment]
I'm quite fine with the app not getting "a lot more attention". Thanks for the suggestion, but the icon stays pink.
