### ISSUE TITLE
Hashtag in post composer isnt formatted as a hashtag

### ISSUE THREAD

**Issue by muznyo** [sk22/megalodon#192]
When you type a word in a composer, but then put a hashtag before it, it doesnt recognize as a hashtag (no color), but when you post it, it is posted as a hashtag as intended.

It's more of a visual bug.

![Screenshot_20221224-004905_Megalodon_edited_1671839372324214.png](https://user-images.githubusercontent.com/24987471/209414079-e1215670-58d2-4404-80d7-182129dd449d.png)

**Comment by sk22** [comment]
upstream bug: https://github.com/mastodon/mastodon-android/issues/221

i also don't really want to fix it myself (if someone wants to, please go ahead, i'll happily merge it!) and instead hope for the official app to fix it

**Comment by muznyo** [comment]
oh, its that old bug? 😯

looks like official android app isnt getting much love

**Comment by sk22** [comment]
hahah, yep 😅

**Comment by realpixelcode** [comment]
> looks like official android app isnt getting much love

At least not that often 😄
