### ISSUE TITLE
Add a preview of a post you are replying to in ComposeFragment

### ISSUE THREAD

**Issue by muznyo** [sk22/megalodon#193]
Currently it just shows: replying to...
![Screenshot_20221224-005223_Megalodon.png](https://user-images.githubusercontent.com/24987471/209414179-05bdae8d-ffb9-42cd-8068-e32f68eb0c64.png)

I think it could show more than that

**Comment by sk22** [comment]
I agree and I'll look into what I can do. In the meantime, you can open the post by clicking that header!

**Comment by muznyo** [comment]
to be honest i didnt even know about the clicking, thats why we need this feature even more! 😅
