### ISSUE TITLE
Render link previews of posts as inset post

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#195]

**Comment by sk22** [comment]
Actually, I think I won't. The discussion about whether quote posts on fedi are wanted or not is too broad for me to confidently implement something that looks a lot like quote posts. I'll leave it at the current implementation (a "Post about this" feature that adds the link to a new post, and rendered as a  normal link preview) for now

**Comment by realpixelcode** [comment]
@sk22 How about posts from services like Calckey that natively support quote boosts? This is what they're supposed to look like vs. what they actually look like in Megalodon:

![image](https://user-images.githubusercontent.com/52963327/209572922-b44049b2-c9ce-4b75-a3d4-321ce3ed521f.png)
![image](https://user-images.githubusercontent.com/52963327/209572931-2ac5e8c1-7180-4a41-a5ba-f94f014dcf7c.png)
