### ISSUE TITLE
Mute and block from context menu not working 

### ISSUE THREAD

**Issue by Ghryphen** [sk22/megalodon#206]
**Describe the bug**
Mute and block from context menu are not working on some locations. I have to go to the user's profile to mute or block.

**To Reproduce**
1. Search via any hashtag (also happens with posts in main feed)
2. Click on '...' on a post
3. Choose mute or block user
4. Menu closes, no confirmation prompt, user doesn't get muted/blocked.

**Screenshots and screen recordings**
![Screenshot_20221227-163205](https://user-images.githubusercontent.com/128811/209739998-b483870b-91f5-487c-b87d-be0bb98bf2e4.png)

**Version**
Megalodon version: 1.1.5+fork.63-play

**Additional context**
- Does this issue also occur with the respective upstream release? 
Official Mastodon app Play Store release doesn't have this issue, when clicking mute from the same menu, there's a confirmation prompt, in Megalodon it does nothing.

**Comment by sk22** [comment]
Noticed that, thanks for letting me know! I don't know how this happened, but I somehow messed up while merging. Fixed this yesterday in 0d2457f39e763aa0192b48f603aca9a3a11b3123
