### ISSUE TITLE
Add a way to differentiate posts with and without comments when interaction counts are disabled

### ISSUE THREAD

**Issue by edxkl** [sk22/megalodon#207]
When interaction counts are disabled, add a way to differentiate posts with and without comments. On Mastodon web and some Android/IOS apps, posts with comments have a plus sign (+) next to the reply icon, so it would be nice if Megalodon could have something similar.

Maybe?
![54151577](https://user-images.githubusercontent.com/80082292/209745944-82aa4dee-c956-4e82-81a3-e6e6fe587a70.png)

**Comment by leachimus** [comment]
But I think it's good to have a number of the comments here. If there is no number, there are no comments. I do not understand their problem.
