### ISSUE TITLE
Icons for favorites, followed hashtags and share profile.

### ISSUE THREAD

**Issue by leachimus** [sk22/megalodon#208]
Please individual icons instead of a menu. It looks better and is easier.

![Screenshot_20221228-112837~01](https://user-images.githubusercontent.com/76697859/209799065-a26c7153-dde3-49fc-b5c8-e9610f0dd814.png)

**Comment by sk22** [comment]
No, I like it better with the overflow menu (I have, however, moved the followed hashtags outside). Too many icons make the toolbar look bloated…. I think. Might still change my mind over this, but closing it for now

![Screenshot_2022-12-28-12-17-34-924_org joinmastodon android sk debug-edit](https://user-images.githubusercontent.com/6217438/209804091-72522ce3-499c-45fa-912c-cd4ba78fd8f0.jpg)

**Comment by leachimus** [comment]
Too many? Its only four Icons. 😆😉
