### ISSUE TITLE
Hide filtered posts with a warning

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#209]

**Comment by thiagojedi** [comment]
There was an attempt: https://github.com/thiagojedi/megalodon/tree/feat/4.0-warn-filters. Got to my limit of android development knowledge. :smiling_face_with_tear: 

I really don't know how to display the warning in a good way. The web interface shows it kinda like a CW. Mammoth on iOS shows it like a normal post, but I don't know how it will behave on a "thread".

**Comment by sk22** [comment]
i'll look into that, thanks!

**Comment by LucasGGamerM** [comment]
There are still a few things I need to polish, but it's basically ready yeah
