### ISSUE TITLE
No translate button

### ISSUE THREAD

**Issue by triadne** [sk22/megalodon#213]
The options allows me to turn the translate button on or off.  Where is it? I can't find any translate button anywhere and I'd like to use it as I need to translate some toots. It seems like it's a bug to me.

**Comment by sk22** [comment]
what instance are you on?

**Comment by sk22** [comment]
when you scroll further to the bottom in the settings, the app should tell you whether your instance supports translation

**Comment by triadne** [comment]
Ah I see that now, thanks! Perhaps thats a feature request then? Either move that notification right underneath the translate button option?
I'm on toot. Wales by the way. Thanks!
