### ISSUE TITLE
Notifications of different categories are overwritten.

### ISSUE THREAD

**Issue by leachimus** [sk22/megalodon#219]
I don't know if it's really a bug or if it's the same in the original app.

If new posts come in I see the familiar shark icon, if likes come in, the previous notification is deleted.

Is there a possibility to show notifications in groups?

**Comment by sk22** [comment]
Not sure if it's the same as that issue over at @LucasGGamerM's Moshidon project, but it looks similar: https://github.com/LucasGGamerM/moshidon/issues/29
I intend to merge the fix into Megalodon. Let me know if this would fix this, too!

**Comment by LucasGGamerM** [comment]
It's still work in progress though, as the notification clicks aren't being handled properly yet*

**Comment by sk22** [comment]
> It's still work in progress though, as the notification clicks aren't being handled properly yet*

what do you mean? just implemented this too, and i don't see any problems (yet)

**Comment by sk22** [comment]
> > It's still work in progress though, as the notification clicks aren't being handled properly yet*
> 
> what do you mean? just implemented this too, and i don't see any problems (yet)

ok, yeah, no, i see the problem now :') also saw https://github.com/LucasGGamerM/moshidon/commit/a48dc18df5e417c5182b5f7cff4639fec807a2b6

**Comment by LucasGGamerM** [comment]
It's being worked on. Maybe later today it will be ready

**Comment by sk22** [comment]
oh, you mean the commit didn't fix it?

**Comment by LucasGGamerM** [comment]
Yeah, that commit didn't fix it. I am still trying to fix it

**Comment by sk22** [comment]
okay.. good luck, and thanks!

**Comment by LucasGGamerM** [comment]
Its properly fixed on 20768182209001d9a7bd6a3d1f3be5548395f5a3, feel free to merge it
