### ISSUE TITLE
Reblog with visibility

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#22]
Enable choosing the desired visibility for boosts. See https://docs.joinmastodon.org/methods/statuses/

**Comment by InterSocial** [comment]
hey, do you have an email to contact you?

**Comment by sk22** [comment]
> hey, do you have an email to contact you?

uhm, yeah, just added it back to my profile!

**Comment by InterSocial** [comment]
> > hey, do you have an email to contact you?
> 
> uhm, yeah, just added it back to my profile!

email sent. thanks

**Comment by sk22** [comment]
oh, that's funny, an upstream commit mistakenly closed this downstream issue
