### ISSUE TITLE
Follow hashtags

### ISSUE THREAD

**Issue by jamfx** [sk22/megalodon#224]
Hi, as described in another issue, I am using Tusky and Megalodon to fit my needs.
In Tusky, there is an option to follow hashtags like in the Webinterface on Mastodon. 
I would love to see this in Megalodon, too.

Best JamFX

**Comment by sk22** [comment]
already there!

**Comment by sk22** [comment]
![Screenshot_2022-12-31-13-14-10-048_org joinmastodon android sk-edit](https://user-images.githubusercontent.com/6217438/210136384-ce3e3423-40ac-43c4-a987-c65dd798f9f5.jpg)
![Screenshot_2022-12-31-13-14-48-956_org joinmastodon android sk-edit](https://user-images.githubusercontent.com/6217438/210136385-84a3707e-7b5c-4394-8676-7b907d3b4a8f.jpg)

**Comment by jamfx** [comment]
Thanks for pointing this out.
