### ISSUE TITLE
Pleroma images/videos don't load up

### ISSUE THREAD

**Issue by samuraikid0** [sk22/megalodon#25]
It's possible to fix it or too soon ?

Thanks !!

**Comment by sk22** [comment]
You mean e.g. images that are beyond the allowed image size on Mastodon? I think this is something that should be fixed upstream, but if you can provide me with an example of a post that doesn't load, I can try to look into it!

**Comment by samuraikid0** [comment]
![Image3040747377869814780](https://user-images.githubusercontent.com/46766062/182028306-f1651ce2-b45e-4a50-9e2e-211a16b334be.jpg)
![Image3191174404016314625](https://user-images.githubusercontent.com/46766062/182028310-961d381c-3f18-47ce-98bd-70bd14189b11.jpg)
![Image7376200749428707054](https://user-images.githubusercontent.com/46766062/182028316-3127fbec-f673-4b21-b11d-63ed256b892f.jpg)

**Comment by samuraikid0** [comment]
![Image2452006469892704782](https://user-images.githubusercontent.com/46766062/182028374-79d5352b-2ad2-4ccf-b34b-28855a82c731.jpg)
![Image7449975943525844321](https://user-images.githubusercontent.com/46766062/182028389-930b7690-e13e-4906-804e-f7f47fed8768.jpg)
![Image7376200749428707054](https://user-images.githubusercontent.com/46766062/182028395-1ee5aac9-7197-4ec8-957e-82b61fc0e17c.jpg)

**Comment by samuraikid0** [comment]
Ill delete the above post once you comment

**Comment by sk22** [comment]
> Ill delete the above post once you comment

seen it! your replies also came via email, so i also got the uncensored posts. :')
