### ISSUE TITLE
Notification setting is reset after every update

### ISSUE THREAD

**Issue by tribela** [sk22/megalodon#252]
**Describe the bug**

**To Reproduce**
1. Set notification setting as "noone"
2. Update app
3. Notification setting is reset

**Version**
Megalodon version: v1.1.5+fork.65

**Additional context**
- Update from f-droid - affected
- Update from app itself - affected

**Comment by sk22** [comment]
Just checked - this appears to also affect the official app. Could you also open an issue there as well, please?

**Comment by sk22** [comment]
seems like this got fixed upstream!
