### ISSUE TITLE
Filters ignored

### ISSUE THREAD

**Issue by haayman** [sk22/megalodon#257]
**Describe the bug**

Filters are ignored.
I've set up a few filters e.g. 'RT ' but those toots still appear in my timeline

**Version**
Megalodon version: [e.g. v1.1.4+fork.#]

**Comment by realpixelcode** [comment]
Upstream bug: https://github.com/mastodon/mastodon-android/issues/94

**Comment by KibSquib48** [comment]
the same happens to me, but they disappear after a refresh

**Comment by sk22** [comment]
> **Version** Megalodon version: [e.g. v1.1.4+fork.#]

so uhm, on which version?
the recent version has a new implementation by @thiagojedi, for which they recently made a pull request for an issue with the implementation - which will be included in the next release: https://github.com/sk22/megalodon/pull/255
does this happen to match the issue you're facing?

**Comment by haayman** [comment]
it's fixed now apparently. I'm on v1.1.5 + fork.65-play(65)

**Comment by sk22** [comment]
ah - nice!

**Comment by KibSquib48** [comment]
> hmm, apparently not. Now I'm seeing filtered toots again

have you tried fork.66? it's a pre-release but it says it fixes filters

**Comment by haayman** [comment]
yes, doesn't fix it unfortunately

**Comment by sk22** [comment]
i hate filters, lol

**Comment by sk22** [comment]
will look into it

**Comment by haayman** [comment]
extra info: turns out that filters that are set to 'Hide completely' don't appear, but filters that are set to 'Hide with a warning' do appear (without the warning). I can imagine that the first filters are set server-side and the others client-side?

**Comment by sk22** [comment]
oh! is it just that? because i know that this is not implemented yet

**Comment by thiagojedi** [comment]
> extra info: turns out that filters that are set to 'Hide completely' don't appear, but filters that are set to 'Hide with a warning' do appear (without the warning). I can imagine that the first filters are set server-side and the others client-side?

Filters were indeed handled by the client-side but it was a little inconsistent. Since Mastodon's v4.0, the filtering is made by the backend and should be more reliable now.

That been said, filters with the 'Hide with a warning' action is a new feature in v4.0. The change has not been implemented yet, as it requires UI changes, as opposed to the 'hide completely' that was the previous (and only) behavior.

**Comment by sk22** [comment]
closing in favor of #209
