### ISSUE TITLE
See all followers of an account 

### ISSUE THREAD

**Issue by zackarired** [sk22/megalodon#258]
**Is your feature request related to a problem? Please describe.**
Currently, if you try to look at who a person follows or who follows them, it only shows people from your instance or people you already follow. It would be great if I can see the full following/follower list so that I could discover people more easily 

**Describe the solution you'd like**
See all followers/following of a person, instead of just a small subset.

**Describe alternatives you've considered**
Currently, I'd have to open the profile in its original instance in web to see the full follow list, then copy handles of those I'm interested in.

**Comment by sk22** [comment]
has been implemented recently!
