### ISSUE TITLE
The ability to create lists

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#276]
**Is your feature request related to a problem? Please describe.**
At the moment, judging by the posts in the mastodon, work is actively underway to integrate lists into the feed, and if we go to the corresponding section of the application, we can only see a list of lists already created in the computer version.

**Describe the solution you'd like**
I want to suggest adding a button to that page that will open the list creation dialog. 

**Describe alternatives you've considered**
Similar solutions already exist in Tusky and Fedilab. The latter even has the most convenient implementation in terms of UX. You can also see Twitter's implementation.
**Additional context**
![Fedilab](https://user-images.githubusercontent.com/62957728/211906113-cf88826d-231d-494e-9119-28f72ceee0df.png)
![How-its-going](https://user-images.githubusercontent.com/62957728/211906117-4a2e879a-a402-4447-9210-f3a4ed175033.png)
![Tusky](https://user-images.githubusercontent.com/62957728/211906118-e8ffda8a-4c81-4047-ae04-2076aa9cc85d.png)
![Twitter](https://user-images.githubusercontent.com/62957728/211906122-f55849fc-6b56-47f2-8d20-36acbf95637a.png)

**Comment by neilideal** [comment]
When I created this proposal, I checked the open issues. I didn't notice anything about the topic, but now I checked the closed ones and there was number [#30](https://github.com/sk22/megalodon/issues/30), of which I am partly a duplicate. You can close this.

**Comment by sk22** [comment]
yep, that's a duplicate, already implemented and will be available in the next release!
