### ISSUE TITLE
Information about post 

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#281]
What do you think of the idea of adapting the information about a post when you open it to what it looks like now in the official app? I think it's easier to read.
1. Official client
2. Megalodon
![Screenshot_20230112-141050.png](https://user-images.githubusercontent.com/62957728/212052331-4b2222f1-eba3-455a-957e-503c0d93b71a.png)
![Screenshot_20230112-141245.png](https://user-images.githubusercontent.com/62957728/212052377-b762021b-6d9c-4560-9bd4-ed81e44a30aa.png)

**Comment by sk22** [comment]
as per https://github.com/mastodon/mastodon-android/compare/master...sk22:megalodon:compact-extended-footer: no, i intentionally made the extended footer more like the old variant after being unhappy with the new one for a long time
