### ISSUE TITLE
Isn't it a visual bug with reblog button?

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#282]
Is it a visual bug with activated reblog button?
How it's working on:
1. Megalodon
2. Official client 
![Screenshot_20230112-142226.png](https://user-images.githubusercontent.com/62957728/212054203-55228f20-1f86-4a39-8d00-e7b11c24b45f.png)
![Screenshot_20230112-142219.png](https://user-images.githubusercontent.com/62957728/212054219-3ebbcf9f-6da9-41af-898d-4274413308b2.png)

**Comment by sk22** [comment]
uhm.. no, this is intentional, to make the reblog button's states more easily distinguishable
