### ISSUE TITLE
[True black mode] Borders below/above title/navbar would be really cool

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#287]

**Comment by realpixelcode** [comment]
Please, for the sake of our eyes, be extremely careful about adding borders! They exponentially increase the visual clutter, providing hardly any additional information at all. It's unbelievable how easy it is to destroy an awesome design with just a handful of badly designed borders/lines.

If you wish to separate the title bar and the nav bar more from the timeline, consider increasing the shadow instead, and if you insist on borders, consider making them as light and as little distracting as possible.

https://www.youtube.com/watch?v=Mv8Pjtvujno

https://designerup.co/blog/ui-design-tips-boxes-and-borders/

**Comment by sk22** [comment]
thanks for the warning - i was only referring to true black mode tho! (where toolbar and navbar aren't distinguishable at all from the content)

**Comment by realpixelcode** [comment]
Ah, right, visual separation is indeed quite hard in dark/black mode 😕
