### ISSUE TITLE
Ability to softblock a person

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#297]
**Is your feature request related to a problem? Please describe.**
How hard is it to implement a feature with the ability to unsubscribe a person? 

**Describe the solution you'd like**
This is done by locking and then unlocking the user, but I would like it as a single button. Placement in the same drop-down menu as the lock button.

**Describe alternatives you've considered**
A similar feature was added to Twitter at some point and I really liked it.

**Comment by neilideal** [comment]
Same for instances

**Comment by sk22** [comment]
oh, you mean soft-blocking, as in "remove follower" on twitter? i could to that, but i don't know how this would apply to instances - like, an instance can't follow you. or do you mean something different?

**Comment by neilideal** [comment]
Yes, I meant the softblock (I wasn't sure if that's what it's called). About the instances.
Example:
I don't like the fact that I have people from some instances subscribed to me. I want to remove them all at once without switching between them. It will turn out that I haven't shut them off from seeing me, but at the same time they are not following me.

**Comment by sk22** [comment]
hmm, i mean we could have a button to block and immediately unblock an instance, but i don't know whether mastodon will handle that correctly (or if it just cancels the scheduled block), so i think i'll rather not implement that. but softblocking individual users sounds good!
