### ISSUE TITLE
New layout for profile?

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#299]
```
[banner]
[ava] [display name]
[ava] [username]
[posts] [following] [followers] [follow button]
[bio]
[metadata]
```

**Comment by sk22** [comment]
as far as i know, the mastodon API only has an endpoint for translating posts (and even within posts, only the actual text is translated, not the CW or image alt text) - so as long as mastodon's translation API doesn't have that; nope, sorry!

**Comment by sloanlance** [comment]
Even if the Mastodon API provides functions only for translating posts, couldn't Megalodon use a different translation service to translate other text?

**Comment by sk22** [comment]
could, yes

**Comment by realpixelcode** [comment]
Two profile pictures? A bit unusual, I'd say.
