### ISSUE TITLE
Image editing 

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#303]
I know it's hard to implement and won't appear anytime soon, but I'd really like to see it!
Screenshots from fedilab.
![Screenshot_20230116-155918.jpg](https://user-images.githubusercontent.com/62957728/212684366-30abc955-a667-47c7-99cb-34befc835bef.jpg)
![Screenshot_20230116-155922.jpg](https://user-images.githubusercontent.com/62957728/212684381-0f127699-169e-4c8a-9231-12460c4fe0f2.jpg)

**Comment by sk22** [comment]
related (including lots of info about possible implementations): https://github.com/mastodon/mastodon-android/issues/185

**Comment by neilideal** [comment]
Then I will close as unplanned, and as the official client will appear, it will be added. Thank you!
