### ISSUE TITLE
Idea for translations

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#304]
Look at this line. Of course, I don't know how the work with lists will be implemented, but maybe it's more correct to write "list <name>" instead of "this list"?
![image](https://user-images.githubusercontent.com/62957728/212735650-a2a70df9-fc84-46fe-9b25-c70cc61997d0.png)

**Comment by sk22** [comment]
you mean "Are you sure you want to delete list"? that's most certainly grammatically incorrect, at least in english

**Comment by neilideal** [comment]
"list + <name_of_list>"
This should work as a confirmation. The person will be able to see again the name of the list they are deleting. He will see, for example:
Do you really want to delete the list <list_name>

**Comment by neilideal** [comment]
Or
Are you sure you want to delete the list <list_name>

**Comment by sk22** [comment]
sounds good, thanks!
