### ISSUE TITLE
Pixelfed account: your personal feed and subscription list do not appear

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#306]
**Describe the bug**
When I log in through my pixelfed account, my personal feed and subscription list don't show up. Interestingly, I can see my local feed and my federated feed. I can see my subscribers too.
And yes, I expect an answer like this is primarily a client for mastodon and no one guarantees the performance of other services. But I just want to note that with the same actions with the account of Pleroma such a problem is not observed.

**To Reproduce feeds**
1. Log in to your pixelfed account
2. Look on your home feed
3. Go to search menu and select any feed

**To Reproduce following**
1. Log in into your pixelfed account
2. Open profile
3. Open following 

**Screenshots and screen recordings**
If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.
Home feed 
![Screenshot_20230117-005916.png](https://user-images.githubusercontent.com/62957728/212772724-702c6bd1-d57c-416b-960b-b05ff4eed40e.png)
Following 
![Screenshot_20230117-005947.png](https://user-images.githubusercontent.com/62957728/212772748-cd9eb4df-0591-4829-858e-8d37473eefac.png)
Followers
![Screenshot_20230117-010004.png](https://user-images.githubusercontent.com/62957728/212772778-5108c12c-a55c-4e6c-909b-8abbf822c104.png)
Local feed
![Screenshot_20230117-011050.png](https://user-images.githubusercontent.com/62957728/212772834-c3fcb393-9406-4255-a953-d4143562c914.png)
Global feed (one more bug with CWs?)
![Screenshot_20230117-011055.png](https://user-images.githubusercontent.com/62957728/212772853-e538ba45-94ef-4ff0-ac62-a5c03670d85c.png)

**Version**
Megalodon version: v1.1.5+fork.66

**Additional context**
On the current upstream (16.01.2023) the same problem. I checked on the second phone.

  > In this case, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead. If this bug is seriously impacting your usage or you think I might want to try to fix it for Megalodon, feel free to still create this issue!
I will also create a similar query for mastodon

**Crash log**
I'll add the crash log later in the comments

**Comment by neilideal** [comment]
[Link with logs](https://drive.google.com/file/d/1rUBJtXd9rpbBKubQ8cla-sj_qFFffDdI/view?usp=drivesdk)

**Comment by neilideal** [comment]
I don't know why but it works now

**Comment by sk22** [comment]
> is primarily a client for mastodon

actually, primarily for non-vanilla mastodon, especially glitch,

> no one guarantees the performance of other services

you're in luck, i actually completely forgot about this issue and actually tried to make pixelfed work somewhat! (i even disable the publish button when a post has no media, because pixelfed doesn't allow posting when there's no media attached, hehe)
