### ISSUE TITLE
Back buttons for hashtag submenus and lists

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#309]
**Is your feature request related to a problem? Please describe.**
When I mistakenly opened the lists instead of the hashtags, I couldn't go back and select what I wanted.

**Describe the solution you'd like**
Simply add a back arrow icon to each of these menus. This will reduce by one step the number of actions to open the desired item in case of error

**Comment by sk22** [comment]
you wouldn't believe how hacky the implementation actually is 😅 but it works!

**Comment by neilideal** [comment]
Thank you for implementing this feature💜
