### ISSUE TITLE
The list of subscribed hashtags is different in the profile menu and in the drop-down menu of the home page

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#312]
**Describe the bug**

**To Reproduce**
1. Go to yours hashtags list in profile and check them
2. Go to home page and open hashtags submenu in drop-down

**Screenshots and screen recordings**

https://user-images.githubusercontent.com/62957728/212899264-ae426eeb-f4c7-4727-afd1-a04364a1c4e4.mp4

**Version**
Megalodon version: Megalodon v1.1.5+fork.68 (68)

**Additional context**
- Does this issue also occur with the respective upstream release? 
No, because this feature is exclusive to megalodon

**Crash log**
If you know your way around Android development tools, please consider attaching a crash log, if possible.
[logs-2023-01-17-15-18-39 (1).zip](https://github.com/sk22/megalodon/files/10434988/logs-2023-01-17-15-18-39.1.zip)

**Comment by sk22** [comment]
pretty sure this only occurs when adding/removing hashtags, right?

**Comment by neilideal** [comment]
That's right
