### ISSUE TITLE
Toggle for local-only posts

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#313]
👁️

**Comment by highlabs** [comment]
Hi! Thanks for creating this feature request. ❤️ 

The local-only toots is a feature from some forks of Mastodon, like [Glitch-soc](https://glitch-soc.github.io), [Hometown](https://github.com/hometown-fork/hometown) and [donte-com-br](https://github.com/masto-donte-com-br/mastodon).

You can find more information about this feature on these links:
- https://glitch-soc.github.io/docs/features/local-only-toots/
- https://github.com/mastodon/mastodon/pull/8427

**Comment by sk22** [comment]
done!
