### ISSUE TITLE
Remove top bar

### ISSUE THREAD

**Issue by pdiamond-op** [sk22/megalodon#320]
It would be great to be able to remove the top bar that says "megalodon" and has the settings icon. It takes up so much space on devices where screen real estate is already at a premium. Remove the bar and move the settings icon into the profile. Once you get the settings the way you like them, you're not going to need that icon very often.

**Comment by neilideal** [comment]
I suggest you check for updates! In the newest version, the megalodon inscription has been replaced by a feed changer element

**Comment by sk22** [comment]
yep; that's kind of not applicable to the latest version. there's also the announcements button up there, so removing the top bar (or adding an option for that) would take too much layout restructuring

**Comment by pdiamond-op** [comment]
> I suggest you check for updates! In the newest version, the megalodon inscription has been replaced by a feed changer element

Thanks. The bar still takes up more room than I'd like, but at least it is much more useful now.

**Comment by neilideal** [comment]
@sk22 What if it worked like Facebook? That is, it would be hiding when you scroll. That would increase the view by a few lines.
https://user-images.githubusercontent.com/62957728/212973961-576e3b0c-1cb6-432d-831f-a935ea538fb4.mp4

**Comment by sk22** [comment]
good to know facebook does it like this! but no, i don't want to remove the navigation bar to the top - also. this would require the top bar to have tab-swiping logics, and this would interfere with the existing sections' scrolling behaviors
