### ISSUE TITLE
Ability to send publications to multiple accounts at once

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#322]
**Describe the solution you'd like**
I don't know if this is technically possible. It's a strange idea and it's hard for me to say if there's even an audience in mastodon that would need such a feature.
**_The way I see it:_**
When writing a post, a person can access multiple choice accounts in these ways:
1. A long press on the "submit" button.
2. Clicking on the down arrows (like on the main feed) within the "send" button will bring up the corresponding menu

The selection of accounts to submit should look like a poll with multiple choices (square elements for highlighting).

**Describe alternatives you've considered**
The idea was spotted by me on Instagram

**Comment by sk22** [comment]
soo, technically it would sure be possible - but would require uploading any attachments to the other servers too. either way, i don't want to implement it (i see some uses, i guess, but i think it would hardly ever be needed), but thanks for the idea!
