### ISSUE TITLE
Indication of whether a post contains a followed hashtag

### ISSUE THREAD

**Issue by Ghryphen** [sk22/megalodon#323]
**Is your feature request related to a problem? Please describe.**

Unable to determine if a post in my feed is from following the user or if it is from a hashtag without remembering all the hashtags I follow. 

I follow several hashtags and there are also several consistent users of those hashtags that I see and have followed, however I am unsure if I still need to follow that user when I see them post again, so I click the context menu and realize, oh yeah, I already followed them.

**Describe the solution you'd like**

Would like to see an indication of what hashtag matches a followed hashtag if the post was shown because of the hashtag and not due to following the person. Maybe a solution could be to highlight/bold/iconify/etc the hashtags that are followed in the message.

As well, would like and indication if I follow that person. There was another discussion about indicating bot accounts, #223, perhaps additional icons for follow state, or, if possible, mutual following state.

**Comment by sk22** [comment]
i actually closed #201 because i thought there's no way i can tell, but maybe like this:

display some kind of "followed hashtag" header when
* at least one of the used hashtags is in followed hashtags
* i don't follow the person who posted this

**Comment by sk22** [comment]
okay, update - i will display a hashtag header when i follow the hashtag that's been posted. but: i unfortunately don't know whether i'm following a user who posted something when scrolling through the timeline. that's also why the "follow/unfollow user" button switches when opening a post's menu. i would have to load the relationship for every single user when scrolling through the timeline, which i won't do.
but i figure it's still nice having a header indicating that the post contains a followed hashtag, even if you're actually also following that user, so i'll still close this as completed!
