### ISSUE TITLE
The app crashed and logged out of all authorized accounts

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#326]
**Describe the bug**
 While viewing the feed, the app crashed and I had to log back into my account. I was automatically kicked out of all my accounts in the app. No specific actions were performed. A replay is unfortunately almost impossible due to the need for a "natural" logout. Logs also can not provide, because at this time did not record the performance (I'm going to allow MatLog to work in the background for these incidents)

**Version**
Megalodon version: [e.g. v1.1.5+fork.68]
Previously encountered on the previous version, but I did not pay the necessary attention to it

**Additional context**
- Does this issue also occur with the respective upstream release? 
This behavior was not seen on the upstream version

**Comment by TheLimifiedLime** [comment]
My app also did the same but I had to reset the data to be able to start the app. I believe I may have been moving around pages quickly when it happened.

Version: v1.1.5+fork.68 on Android 13

**Comment by sk22** [comment]
probably recently fixed this! (apparently, when the app crashes / is closed while it's currently writing the accounts.json file, it effectively logs you out of all accounts. i worked around this by first writing to a different file and then renaming it to accounts.json once it's finished writing)
