### ISSUE TITLE
Add a way to easily switch timelines in the navbar

### ISSUE THREAD

**Issue by deanveloper** [sk22/megalodon#329]
**Is your feature request related to a problem? Please describe.**

I get frustrated when I have to switch timelines because it is at the top of the screen, and phones are often quite large nowadays. 

**Describe the solution you'd like**

It would be very good to have a timeline switcher at the bottom of the screen, which functions similar to the account switcher but on the home button. Specifically:

1. holding the home button should bring up the timeline switcher
2. switching the timeline should change the navbar icon to that timelines icon (ie, the group of people for local, and the earth for federated)
3. There should be arrows next to the home icon (similarly to the profile icon) to signify that there is a hold-menu there.

Additionally, it would be nice if double-tapping the home button (or, the "timeline button" as it should probably be called) would return to the Home timeline.

**Describe alternatives you've considered**
If applicable: a clear and concise description of any alternative solutions or features you've considered.

I mean, we already have an alternative right now and I'm not super happy with it. The timeline switcher is quite far away and can be hard to reach.

There are reachability features in mobile OSs which can can alleviate the issue of the top being hard to reach, however I don't typically like using them because they're a bit too easy to trigger accidentally which is frustrating.

Perhaps I should also additionally make a feature request to mastodon-android since this doesn't seem like a feature that needs to be megalodon specific.

**Additional context**

N/A (I don't think any other additional information is needed, but if I'm wrong I'm more than happy to answer any questions this may cause)

**Comment by neilideal** [comment]
You can also swipe left and right to switch between feeds

**Comment by deanveloper** [comment]
Oops, I didn't know this 😅 feel free to close if it's probably not worth looking in to.

With Tusky I had to disable swiping between tabs because I'd constantly accidentally swipe between them since the side-swiping was a bit too sensitive. Although it looks like the tolerances on what's considered a side-swipe is a bit more strict which is a lot nicer.

**Comment by sk22** [comment]
related: #310
