### ISSUE TITLE
Separate Search and Explore sections?

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#33]
This would lead to less confusion regarding the state (search/explore page) that gets switched when focusing the search box.
Also, this would enable the Explore page to have action buttons (like to filter the timelines or to manage followed hashtags?

**Comment by leachimus** [comment]
I think their proposal is a good one and I endorse it.

**Comment by sk22** [comment]
since i moved public timeline out of this section a while ago, i think explore + search can stay combined
