### ISSUE TITLE
Restyling of the open post page

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#332]
**Is your feature request related to a problem? Please describe.**
I recently saw a video with a similar idea for a Twitter. Might be interesting
**Describe the solution you'd like**
I know you get so many notifications with mentions, and you can't pay attention to everything. I recently sent you in this way a link to a video of a designer's idea to redesign a similar page for Twitter. It takes about a minute of your time.
If you are interested, I will make such a project for Megalodon in penpot and send you a link to it or screenshots (at your discretion)

**Describe alternatives you've considered**
[Video](https://www.youtube.com/shorts/BzYDxLH-tdw) from YouTube
**Additional context**
Final vs. Old view screenshot from that video
![image](https://user-images.githubusercontent.com/62957728/213460929-96fa3fdb-e910-4374-a16b-d47bf676f640.png)

**Comment by sk22** [comment]
thanks for the idea! i am, however, quite happy with how the ThreadFragment looks at the moment! also, i'm not that big of a fan of the video you linked tbh :') also sounds like a lot of work (like the "moving the header to the top" part), which, then, also brings up questions: like, if you open a post that's a reply in a thread, whose profile should be displayed? etc. too many things to consider. though, if you have any concrete suggestions, do let me know!
