### ISSUE TITLE
Client-side instance blocklist

### ISSUE THREAD

**Issue by neurer** [sk22/megalodon#333]
Apart from being briefly mentioned in the [changelog](https://github.com/sk22/megalodon/releases/tag/v1.1.5%2Bfork.68) I couldn't find any other documentation on this. So looking at https://github.com/mastodon/mastodon-android/commit/e7bb393cee5709c5ef46efdffa89bbd38f946636 it appears as if there's now a hard-coded instance blocklist in the client.

A couple of thoughts on this:

1. Please consider including it in the documentation.
2. This could be something users may want to opt-out of.
3. This may be something better left to instances entirely.

**Comment by sk22** [comment]
the reason i included the block list in the first place is that users of abusive instances can't easily use my app.
while the block list denies all traffic to those servers, it's mostly affects logging in to those instances.
this doesn't even mean that posts from those instances can't appear on your timelines - posts are loaded by your home instance anyway: your mastodon client app asks your home instance for the posts and doesn't talk to the origin server at all. the only thing i think can happen in that regard is that media from the blocked instance doesn't load
