### ISSUE TITLE
The same set of posts is shown twice

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#335]
**Describe the bug**
I'm not an author. Problem was found by that user:
https://mstdn.social/@jukkan/109722988454813204

**Version**
Megalodon version: v1.1.5+fork.68-play

As for all the other points. I will try to reproduce this and also check the upstream.

**Comment by sk22** [comment]
you mean the age-old issues mastodon#142 and mastodon#180?

**Comment by neilideal** [comment]
That sounds like a description. It probably does. And upstream hasn't fixed that yet? Weird

**Comment by sk22** [comment]
in this case i'm closing this issue, i don't really have the motivation to try to fix this ^^'
