### ISSUE TITLE
Slight frame stutter on local and federated timelines

### ISSUE THREAD

**Issue by deanveloper** [sk22/megalodon#365]
**Describe the bug**

When scrolling through local/federated timelines, the screen seems to stutter a bit. I didn't notice for the longest time but now I can't unsee it :(

**To reproduce**

1. Go to local or federated timeline
2. Scroll up/down

**Does this happen in the official app?**

No, as local/federated timeline don't exist in the official app

**Screenshots and screen recordings**

If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

I was thinking that maybe 120fps wasn't being enabled by the system when scrolling through Local/Federated timelines, however after turning on the display refresh rate setting, it seems to be using 120fps:

![Screenshot_20230123-123723](https://user-images.githubusercontent.com/3196327/214144736-c4244638-c692-4585-95c3-75f016f9ca51.png)

**Version**

Megalodon version: v1.1.5+fork.68-play (68)

**Comment by sk22** [comment]
so, problem is i have no idea how i would go about fixing this, and i'm not 100% sure what exactly you mean or whether this affects me too or not.

now the local timeline does actually exist in the official app: it's the tab called "community" in the search section. would you try and see if it affects that one, too?

**Comment by deanveloper** [comment]
I'll see if it shows in a screen recording, it's a really slight stutter that only seems to occur on the local/federated timeline.

**Comment by deanveloper** [comment]
Yeah it's been a bit and haven't noticed it happening anymore, maybe it was just a one-time thing? It was happening for a while though. I'll close this anyway and update if I see it happen again
