### ISSUE TITLE
Group notification events

### ISSUE THREAD

**Issue by d4f5409d** [sk22/megalodon#378]
**Is your feature request related to a problem? Please describe.**
It's often overwhelming to browse through all the new followers and favorites/boosts in the notification tab. 

**Describe the solution you'd like**
It'd be amazing to group together follows, favorites and boosts happened a while ago.

**Describe alternatives you've considered**
-

**Additional context**
Like here: https://mastodon.social/@mttvll/109756539355733030

**Comment by sk22** [comment]
this might be a duplicate of #37
