### ISSUE TITLE
Following/followers not visible 

### ISSUE THREAD

**Issue by triadne** [sk22/megalodon#381]
Following or followers is pushed off the edge of the screen on profile page. It should at least be able to go smaller to fit on the screen.

**Comment by sk22** [comment]
could you include a screenshot so i know how it looks and what causes it?
planning to redesign the profile page anyway, so this might be something to keep in mind then

**Comment by triadne** [comment]
Oh I see I can post an image! Here you go! 
![Screenshot_20230127_125019_Megalodon](https://user-images.githubusercontent.com/29523389/215091307-87799a12-08bd-4f2c-86f8-1f42a0f83bdd.jpg)
