### ISSUE TITLE
Alt Textbox cut off on images with low height

### ISSUE THREAD

**Issue by MKCOOL142** [sk22/megalodon#386]
On images which aren't tall the Textbox can get easily be cut off and be inconvenient to read

1. Look at a post with a short image
2. Click on alt
4. See awkward ui

This doesn't happen upstream cuz the alt button isn't a thing there 

Version 1.1.5+fork.74 

![Screenshot_20230127-220015](https://user-images.githubusercontent.com/40364718/215198734-61288e8d-9d73-4fb7-a969-6f9381234915.png)

**Comment by sk22** [comment]
that's an upstream issue https://github.com/mastodon/mastodon-android/issues/514 - which i honestly don't want to take care of myself. therefore closing this

**Comment by sk22** [comment]
(the alt button isn't a thing there *yet* - it has been implemented upstream, but not released yet)

**Comment by MKCOOL142** [comment]
That explains it, I couldn't see the button in mastodon so I thought it was implemented by you
