### ISSUE TITLE
Certain Instance doesn't get detected when pressing link

### ISSUE THREAD

**Issue by MKCOOL142** [sk22/megalodon#392]
The instance https://indieweb.social/ doesn't seem to be detected by the app as a mastodon instance

**To reproduce**

1. Tap on a https://indieweb.social/@username link

I wouldn't exactly say this is "upstream" even tho technically this feature is iirc just forked from tusky but I'm not sure 
**Version**

Megalodon version: [v1.1.5+fork.74]

**Comment by sk22** [comment]
that's probably caused by your home instance not federating with indieweb.social. if you copy the link and paste it into search, do you get any results? (because that's effectively what the look-up is doing) if not, it opens the link in the browser as a fallback

**Comment by sk22** [comment]
because, on floss.social, when i open https://indieweb.social/@username (with a valid username) it does work as it should

**Comment by MKCOOL142** [comment]
Yes it does work now, does the lookup automatically abort after a hardcoded time like a second for example? I do have a poor internet connection and it seems that half the time it stays in the app and the other half it opens the browser?

**Comment by sk22** [comment]
as far as i know, there's a timeout for all API requests, but i actually don't know for sure. i'll keep this in mind, though; maybe i'll set it to be something higher
