### ISSUE TITLE
Concept idea for ui plugins

### ISSUE THREAD

**Issue by MKCOOL142** [sk22/megalodon#395]
This is almost definitely too ambitious but I want to share the idea regardless. I think it'd be good to have some kind of centralized app for fediverse plattforms and use megalodon (or Mastodon) as a base, essentially having a plugin system where pixelfed or peertube or Lemmy wouldn't have to go and develope their own individual apps rather they'd create a plugin which would modify certain ui elements like f.e a grid view for an accounts posts on pixelfed, or a more reddit like reply section for Lemmy, or a video player with more options for peertube. And these plugins could be tied to different accounts so f.e opening a pixelfed.de user profile might open a prompt asking if you want to apply the pixelfed ui plugin ect. Idk I guess this is probably too much work, maybe I'll post this to the Regular mastodon apps repo too, I just think it'd get dismissed under the reason that the app is made for mastodon and ONLY for mastodon so yea

**Comment by sk22** [comment]
so thing is i like the idea of having the mastodon app's design and functionality and being able to use it for other services as well, but i really don't think megalodon or the official mastodon app are a good base for a plugin system. no offense to the upstream dev, but some parts of the code could *really* use some refactoring (which i don't want to do in the fork because i still want to be able to easily merge upstream changes). so that's a clear no from my end (but thanks for the idea!), but i'm also very sure that the official mastodon app dev and maintainers won't have much interest in this either, but for different, business-y reasons ^^'

**Comment by sk22** [comment]
note that i do intend to improve compatibility with other, non-mastodon servers (first and foremost akkoma) too, though!

**Comment by MKCOOL142** [comment]
> so thing is i like the idea of having the mastodon app's design and functionality and being able to use it for other services as well, but i really don't think megalodon or the official mastodon app are a good base for a plugin system. no offense to the upstream dev, but some parts of the code could _really_ use some refactoring (which i don't want to do in the fork because i still want to be able to easily merge upstream changes). so that's a clear no from my end (but thanks for the idea!), but i'm also very sure that the official mastodon app dev and maintainers won't have much interest in this either, but for different, business-y reasons ^^'

Yeah I totally get it, I mean it makes sense, the app is called mastodon, not fedidon or something so obviously it's aimed at mastodon, I just find it to honestly be the best working fedi client currently, it's not bug free but it's pretty lightweight and has a good ui, and I'd love to have those things for other fedi services, I don't want another silly web wrapper or some buggy mess that looks dated before it even released. Idk this feels more like a rant so, sorry about that

**Comment by MKCOOL142** [comment]
As harsh as it sounds, this is honestly the best looking mastodon client we have on Android, I know design is subjective and might not matter to everyone but some clients are just unbearable to look at

**Comment by sk22** [comment]
i know :') maybe i should've used tusky as a basis instead and applied mastodon's look somehow…

**Comment by MKCOOL142** [comment]
Maybe I should learn java (or probably kotlin would be better since it's more modern but the current masto devs seem to fucking hate kotlin) and do it myself (if only it was so simple haha)
