### ISSUE TITLE
Rename attach media to attach image

### ISSUE THREAD

**Issue by MKCOOL142** [sk22/megalodon#397]
Calling the option "attach media" rather than image doesn't make a lot of sense as the android photo picker can only pick images, media suggests that video and audio would work with the option too as those are also considered media, but they don't appear in the menu at all, instead I think the select file option should be renamed to media, and the current media option to images

**Comment by MKCOOL142** [comment]
False alarm I just learned the "photo picker" can pick videos too huh

**Comment by sk22** [comment]
oh, alright then!
