### ISSUE TITLE
add support for translating and copying image ALT text

### ISSUE THREAD

**Issue by sloanlance** [sk22/megalodon#400]
**Is your feature request related to a problem? Please describe.**
I would like to see translation features for image ALT text and the ability to copy that text (translated or not).

**Describe the solution you'd like**
Add links or buttons to the image ALT text display that would let the user request a translation of the text and to copy the text shown at the moment, either translated or untranslated.

**Additional context**
From my post about this yesterday (https://mastodon.social/@sloanlance/109779681145770501)…

> [@megalodon](https://mastodon.social/@megalodon@floss.social), it'd be helpful to have translate/copy available for image ALT data, too.
>
> For example, see the following post I happened to find in the "local" feed…
>
> https://mastodon.social/@lammatini/109778882714624630
>
> I could use the translate feature to see the post in English, but I couldn't do anything with the image ALT data. There was no translate feature for it and I also couldn't copy it.
>
> What to do?

**Comment by sk22** [comment]
the only translation feature megalodon supports is the one provided by the mastodon server - and unfortunately, it only returns the post's translated content at the moment, so no translation for alt texts (or even content warnings).

i've just made the text in the new alt badge (which is a new feature from the official app) selectable (i.e. copiable/sendable to your local translation app) – which has always been enabled for the image description viewer that you can access using the button on the top right when opening a photo/video

**Comment by sk22** [comment]
> i've just made the text in the new alt badge (which is a new feature from the official app) selectable (i.e. copiable/sendable to your local translation app) – which has always been enabled for the image description viewer that you can access using the button on the top right when opening a photo/video

had to revert it again; having it selectable breaks scrolling
