### ISSUE TITLE
Multiple hashtags in single timeline

### ISSUE THREAD

**Issue by d4f5409d** [sk22/megalodon#416]
**Is your feature request related to a problem? Please describe.**
Yes, currently, when we want to check on some hashtags we follow, we have to do it wirh every hashtag we want to look up on. But when we want only the summary of all in a timeline form, we can't do that. (Hint: Tusky does have this feature)

**Describe the solution you'd like**
Have a followed hashtags timeline option.

**Describe alternatives you've considered**
Add all hashtags option to followed hashtags menu (but it's not very intuitive in my opinion)

**Additional context**
-

**Comment by sk22** [comment]
mh, where does tusky have that? can you show me a screenshot or something?

**Comment by d4f5409d** [comment]
> mh, where does tusky have that? can you show me a screenshot or something?

    ![IMG_20230213_170503.jpg](https://user-images.githubusercontent.com/76624594/218509649-e9effb73-cf8d-46c1-baba-36941ddff787.jpg)

**Comment by sk22** [comment]
ohh, but when adding a hashtag timeline, you have to enter a specific hashtag anyway. in megalodon, you can just open a hashtag elsewhere and press the pin button.
i understood something about a timeline containing posts from all followed hashtags, which i don't think tusky has, does it?

**Comment by d4f5409d** [comment]
> mh, where does tusky have that? can you show me a screenshot or something?

    ![IMG_20230213_170503.jpg](https://user-images.githubusercontent.com/76624594/218509649-e9effb73-cf8d-46c1-baba-36941ddff787.jpg)

    Yes, you can add multiple tags to that. This way it displays all the posts from all the hashtags.

**Comment by sk22** [comment]
recently implemented this, will be available in the next release!

![Screenshot_20230622-194720_Megalodon](https://github.com/sk22/megalodon/assets/6217438/cb15b4fb-b55b-4ada-b7e3-837a6dec9cd3)

**Comment by d4f5409d** [comment]
Thank you ❤️🔥
