### ISSUE TITLE
Images are stretched

### ISSUE THREAD

**Issue by nonetrix** [sk22/megalodon#425]
**Describe the bug**

Image's in the timeline are stretched and look strange

**To reproduce**

1. Install megalodon
2. Sign in
3. Scroll a bit
4. See image is stretched

**Does this happen in the official app?**

No, but to be fair the image I used for testing doesn't even display at all there but others don't

**Screenshots and screen recordings**
![Screenshot_20230210-223607~2](https://user-images.githubusercontent.com/45698918/218240193-23e4146e-d125-4e15-81a2-61c7d582603b.png)
![Screenshot_20230210-223622](https://user-images.githubusercontent.com/45698918/218240199-f8660160-d127-4a5c-980d-557813fd3112.png)
![Screenshot_20230210-223625](https://user-images.githubusercontent.com/45698918/218240211-29abc60e-05c6-4f19-81d2-ace0f5341fd8.png)

If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

**Version**

Megalodon version: Megalodon v1.1.5+fork.74 (74)

**Comment by sk22** [comment]
ah, so this is happening when the server (not mastodon) doesn't specify the image size…
this should also affect upstream as of this commit https://github.com/mastodon/mastodon-android/commit/7bb280e8b8248ed27c4261419fc59895084b0e03; would you try using the upstream apk provided in the megalodon's releases section?

**Comment by nonetrix** [comment]
Newest release didn't provide a upstream APK for whatever reason(v1.1.5+fork.75) but one below that did(v1.1.5+fork.74) but images just didn't display if they where bugged on megalodon

**Comment by nonetrix** [comment]
Also, for more information if this is related to the server I am using Pleroma+soapbox 2.5.50-190-g4c0ab884.develop as backend

**Comment by sk22** [comment]
i don't plan to fix bugs occurring on pleroma/soapbox as those are developed by someone who loves interacting with nazis. i'm assuming this also occurs with akkoma, but again, i'm pretty sure the linked upstream commit introduces the problem. i'll provide an upstream build with the next release, so i'd be thankful if you could test it again then

**Comment by nonetrix** [comment]
I don't care who writes my software. They can be a Nazi, they can be a communist, they can be a anarcho capitalist. Why does it matter to you?

**Comment by nonetrix** [comment]
If you aren't willing to fix a bug with your software over political disagreements your software is clearly not worth using so goodbye I won't be using your software
