### ISSUE TITLE
Add noto emojis support for low versions Android

### ISSUE THREAD

**Issue by kyvx** [sk22/megalodon#426]
In lower version Android, there will miss some emojis. I see Tusky can automatically substitute these missing fonts with Noto Emojis.

**Comment by sk22** [comment]
closely related to the upstream issue mastodon#470, which i don't think i'll be able to do myself.
closing this in favor of #459, which doesn't necessarily describe your issue, but would also solve it. again, related to mastodon#470, which i think is out of my reach
