### ISSUE TITLE
Emojis are not pasted in poll options

### ISSUE THREAD

**Issue by BANOnotIT** [sk22/megalodon#433]
**Describe the bug**

When I try to paste server emoji in poll option it pastes it in post main text instead. 

**To reproduce**

1. Go to post creation
2. Add poll to the post
3. Focus on option text
4. Open emoji selection and tap on one

The emoji will be pasted in place of last cursor position in main post text instead of current position which is inside option text. 

**Version**

Megalodon version: v1.1.5+fork.76-play

**Comment by sk22** [comment]
as per the "Does this happen in the official app?" section of the bug report template that you deleted: would you please open an issue in the [official app's repo](https://github.com/mastodon/mastodon-android/issues) instead?

like, yes, this bug affects megalodon too, but it's not really something i'm too interested in fixing myself, like most of the bugs listed in the official app's issues.

**Comment by BANOnotIT** [comment]
This bug is fixed in official client now
