### ISSUE TITLE
Show multiple indicators for boosted replies

### ISSUE THREAD

**Issue by KyleDavidE** [sk22/megalodon#448]
**Is your feature request related to a problem? Please describe.**
In the home timeline it is impossible to tell if a boosted post is a reply or not.

**Describe the solution you'd like**
Either show two context rows like

```
🔄 XYZ rebloged
↩️ In reply to ABC
```

Or just show the icon

```
↩️ 🔄 XYZ rebloged
```

Or a single line combined message

```
🔄 ↩️ XYZ rebloged a reply to ABC
```

**Comment by sk22** [comment]
just tried implementing this when i noticed that i think this isn't easily possible because the app doesn't know anything (it'd need the name) about the account who the post is a reply to, see https://github.com/mastodon/mastodon-android/issues/342.
i could just display the ↩️ header, tho…

**Comment by sk22** [comment]
![Screenshot_2023-03-14-14-59-53-461_org joinmastodon android sk debug-edit](https://user-images.githubusercontent.com/6217438/225025035-69635544-af67-416b-a1d8-1df40c6c1835.jpg)

hmm… how's this?

**Comment by fleurc** [comment]
@sk22 I like the second try with the indentation a lot more, it looks brilliant.

![f9724df25a449f1d](https://user-images.githubusercontent.com/35513885/225033878-90981b28-3097-4fb9-bb5b-87f6ec17ed0e.jpg)

**Comment by sk22** [comment]
committed & pushed :)
