### ISSUE TITLE
[Feature Request] Open Links Outside the App in App

### ISSUE THREAD

**Issue by KaiserCalm** [sk22/megalodon#450]
Using the Android Verified Links feature, it would be possible to add support for opening Mastodon links from other places besides the app itself, which would be a great feature!

![Screenshot_20230302-170815_Settings](https://user-images.githubusercontent.com/81613945/222467546-4e85beb5-f445-43f0-bc11-59cc36141df8.png)

**Comment by KibSquib48** [comment]
Wouldn't this need a hardcoded list of instances to open links from?

**Comment by FineFindus** [comment]
> Wouldn't this need a hardcoded list of instances to open links from?

Yes. AFAIK, it's currently not possible to check at runtime, if a URL should be opened in the app. Also, [it is required for apps to verify their ownership of the domains](https://developer.android.com/training/app-links#android-app-links), which is not possible in this case.

**Comment by sk22** [comment]
given @FineFindus' reply, closing this as it seems like this isn't really possible anyway. if other apps come up with another way of doing this, i'll reconsider it!
