### ISSUE TITLE
Setting notifications 

### ISSUE THREAD

**Issue by topcaser** [sk22/megalodon#451]
Hi, I currently get notifications to my subscriptions (if I follow someone) on my OPPO x2 find pro. But I have a Pixel 7 pro as well which is running GrapheneOS and with that device I don't get  notifications to my subscriptions. The question is why and how the notifications are working. Do I miss a setting or is it about firebase or does this software don't rely on firebase at all?

**Comment by FiraliaDev** [comment]
Same issue here on my Motorola Edge 20. I never receive push notifications for profiles I've turned them on for. Sometimes they don't even show up in the notifications section of the app :/

**Comment by sk22** [comment]
it relies on firebase cloud messaging at the moment; just like the upstream app does. it should work with microG, as far as i know, but i haven't tested it. also, there are efforts by @LucasGGamerM to support UnifiedPush, see #108.
closing this issue as i'm assuming it's about FCM on your GrapheneOS. also, as asked in my bug report template, please try if the issue also occurs on the official app.

**Comment by LucasGGamerM** [comment]
I can confirm notifications work through microG and currently rely on firebase to actually be delivered
