### ISSUE TITLE
Auto-play animated GIFs is set but GIFs do not auto-play in megalodon

### ISSUE THREAD

**Issue by bryancallahan** [sk22/megalodon#452]
**Describe the bug**

Visiting https://mstdn.social/@stakecam from a browser, I see animated gifs autoplay in the stream. I've confirmed my account has Preferences > Appearance > Auto-play animated GIFs checked. In the android megalodon client (latest from play store), the gifs do not autoplay from this account (or any other animated gifs). Is this working-as-intended? (If so we can close; if not, I can get more details.)

**To reproduce**

1. Go to https://mstdn.social/@stakecam (can be any account with animated gifs, this one just has a good collection)
2. View stream

**Does this happen in the official app?**

Will check this after I can confirm whether this is working-as-intended. (Wanted to get this captured since I didn't see it mentioned yet.)

**Screenshots and screen recordings**

If helpful can add, but pretty quick to repro. :)

**Version**

Megalodon version: v1.2.0+fork.77-play (77)

**Crash log**

n/a

**Comment by bryancallahan** [comment]
Happens in v1.2.0 (50) client (latest from play store). Filing bug over there: https://github.com/mastodon/mastodon-android/issues/541. Thanks! :)

**Comment by d4f5409d** [comment]
Can we reopen this? This annoys me as well and looks like it won't get implemented by grishka anytime soon
