### ISSUE TITLE
Add "Copy link to post/profile" button

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#46]

**Comment by muznyo** [comment]
you can already do it with share, can't you?

**Comment by sk22** [comment]
> you can already do it with share, can't you?

usually, but for some reason xiaomi's MIUI doesn't have a "copy link" share option, which is.. annoying to say the least

**Comment by sk22** [comment]
Copy function for posts is implemented. Not for profiles, but you can copy the username and open a profile in the browser, which I think is enough for profiles
