### ISSUE TITLE
Implement instance about page

### ISSUE THREAD

**Issue by d4f5409d** [sk22/megalodon#464]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Currently we only can see rules and other usefult things like instance banner, description etc. when we are on the web version or when we are registering.

**Describe the solution you'd like**
The about instance button in the settings should open up an in app page, that contains all of these informations in the environment of Megalodon.

**Describe alternatives you've considered**
If applicable: a clear and concise description of any alternative solutions or features you've considered.
-

**Additional context**
![IMG_20230319_185730.jpg](https://user-images.githubusercontent.com/76624594/226197315-1feaa34b-0997-40b1-b4ba-e91fa3a768ae.jpg)

![IMG_20230319_185702.jpg](https://user-images.githubusercontent.com/76624594/226197328-517bf47d-2ab6-462a-aba4-bf737b37e6bc.jpg)

**Comment by neilideal** [comment]
It feels like this issue might be closed because of the switch to the new Mastodon design, which has this capability

**Comment by d4f5409d** [comment]
We should wait until we get it here.

**Comment by sk22** [comment]
implementation/adaptation is done (bonus: when you click any person's username in their profile, you can view their instance's about page!), so i'm closing this now. will, of course, only be available in the next release (not yet sure when that will be ready.. might still be a few weeks)
