### ISSUE TITLE
Remember translated posts

### ISSUE THREAD

**Issue by d4f5409d** [sk22/megalodon#466]
**Is your feature request related to a problem? Please describe.**
Currently if we translate a post in a timeline and click on them to make it bigger and expand it to see the replies, it switches back to original language and we have to translate it **again**. Which is very frustrating. *very.*

**Describe the solution you'd like**
Cache the translation?

**Describe alternatives you've considered**
If applicable: a clear and concise description of any alternative solutions or features you've considered.
Render the same element in timelines just make them look like collapsed

**Additional context**

**Comment by sk22** [comment]
thanks for noting this!

**Comment by d4f5409d** [comment]
It's wonderful, however backwards this doesn't work! It's a minor thing indeed, but ;)
