### ISSUE TITLE
Profile pages not loading on fork 80

### ISSUE THREAD

**Issue by ExperiencersInternational** [sk22/megalodon#469]
**Describe the bug**

Decided to file it officially, fork 80 has a bug with profile pages not loading.

**To reproduce**

1. Download fork 80
2. Click on a profile and handle
3. App crashes

**Does this happen in the official app?**

Unknown, likely not since it only started happening in this version.

**Version**

Megalodon version: v1.2.0+fork.80

**Crash log**

If you know your way around Android development tools, please consider attaching a crash log, if possible.

**Comment by sk22** [comment]
thanks, thanks, won't be hard to fix; i'm assuming the ProfileFragment just doesn't initialize the swipe layout thingy so i should just check for it to be null before accessing it. not today tho
