### ISSUE TITLE
Compose UI not using the translated language strings

### ISSUE THREAD

**Issue by d4f5409d** [sk22/megalodon#476]
**Describe the bug**

The compose UI displays in the language picker the english version instead of device language version.

**To reproduce**

Go to compose UI with another device language

**Does this happen in the official app?**

> No 

> In case it does, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Megalodon, feel free to still create this issue!

**Screenshots and screen recordings**

If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

![Screenshot_2023-03-24-20-46-49-31_97294d061ac208a4e8e283a3feb896c9.jpg](https://user-images.githubusercontent.com/76624594/227625247-87c5d18e-5e21-4c3d-98b2-14f9a2703205.jpg)

**Version**

Megalodon version: [e.g. v1.2.0+fork.83]

**Crash log**

If you know your way around Android development tools, please consider attaching a crash log, if possible.

-

**Comment by sk22** [comment]
the compose UI shows the picked language's native name (not necessarily english), which is intentional. if you have a strong opinion why i should display the language in the display language instead, feel free to share it, but i thought it'd be a nice touch to have the language be displayed in the same language as the post's text

**Comment by d4f5409d** [comment]
> the compose UI shows the picked language's native name (not necessarily english), which is intentional. if you have a strong opinion why i should display the language in the display language instead, feel free to share it, but i thought it'd be a nice touch to have the language be displayed in the same language as the post's text

The problem is that we don't see the native name when the context menu is not opened. We see the english version of every langauge.
