### ISSUE TITLE
Do not translate emojis/emoji only posts

### ISSUE THREAD

**Issue by d4f5409d** [sk22/megalodon#477]
**Describe the bug**

Currently Megalodon wants to translate posts made up from emojis. Which are, useless.

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
(Please test using the respective `upstream-xxxxxx.apk` provided in [Releases](https://github.com/sk22/megalodon/releases) or at least using the current Mastodon version from the Play Store)

> No

> In case it does, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Megalodon, feel free to still create this issue!

**Screenshots and screen recordings**

If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

**Version**

Megalodon version: [e.g. v1.2.0+fork.83]

**Crash log**

If you know your way around Android development tools, please consider attaching a crash log, if possible.

**Comment by sk22** [comment]
closing this too - emoji-only posts aren't really all that common anyway, so i don't really see a point in checking whether a post actually contains text before offering to translate it
