### ISSUE TITLE
Make the animations of buttons more like on the web

### ISSUE THREAD

**Issue by d4f5409d** [sk22/megalodon#479]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
I mean by that a spinning favorite button and moving boost button, everything else is great

**Describe alternatives you've considered**
If applicable: a clear and concise description of any alternative solutions or features you've considered.
-

**Additional context**

**Comment by sk22** [comment]
i think i won't ever want to implement this. i like it the way it is - i actually once tried implementing the star-spin-effect, but i ended up not really liking how it looks.
but [moshidon](https://github.com/LucasGGamerM/moshidon) has that!
