### ISSUE TITLE
[not an issue/FR] Thanks for a great app!

### ISSUE THREAD

**Issue by zopieux** [sk22/megalodon#481]
Hi,

Feel free to close this "issue". I wanted to share some positive feedback from using the app after a frustrating experience with the official Mastodon (PlayStore) one.

* Most defaults are sane and nice. I removed the red warning for missing alt texts because they're too obnoxious but otherwise didn't change much and I like the look and feel.
* Scrolling/dragging is smooth and intuitive. I absolutely despised the weird, laggy feel of the official app.
* The app is not even 6MB yet it just works and is full of features. This is the first time in years I witness a non toy app under 10MB.
* Plenty of useful settings, without clunky nested menus. Great!
* Auth flow just worked.
* Option to reduce animations is underrated. I like my apps snappy and don't mind the lack of transitions. Thanks!
* Boost banner brings to the booster's profile. This is absolutely necessary, I can't believe this is missing on other clients.

Keep up the good work! 👍

**Comment by sk22** [comment]
thanks so much for the feedback!!

> Scrolling/dragging is smooth and intuitive. I absolutely despised the weird, laggy feel of the official app.

i didn't change anything regarding this actually; all the smoothness is thanks to the official app. not sure what you were experiencing…
