### ISSUE TITLE
Duplicate entry in language selector

### ISSUE THREAD

**Issue by fhemberger** [sk22/megalodon#487]
**Describe the bug**

When composing a new message, "English" always appears twice in the language selector. Don't know if this is related to #135.

![Screenshot_20230404-204928](https://user-images.githubusercontent.com/153481/230024979-d7862b15-00a7-4d7a-affc-d24ff514d592.jpg)

**Does this happen in the official app?**

No.

**Version**

Megalodon version: v1.2.0+fork.83

**Comment by sk22** [comment]
hmm, interesting… what languages have you set as default in your system settings? because it displays those per default - maybe you have two different englishs in your preferred languages list? (like "english (united states)" and "english (germany)")?

**Comment by fhemberger** [comment]
@sk22 Oooh, yes, that was indeed the case, thanks! Closing.
(Whatever "English (Germany)" is supposed to be ... "Denglish"? 😂 )

**Comment by sk22** [comment]
fixed this simply by adding `.distinct()`, which i didn't even know the java streaming api had. java surprised me positively for once :D
