### ISSUE TITLE
Show how many favourite and reblogs numbers in post without clicking into the post like in the original mastodon application 

### ISSUE THREAD

**Issue by DLRAM** [sk22/megalodon#492]
![IMG_20230409_121930.jpg](https://user-images.githubusercontent.com/59944300/230758789-f2a01be5-5024-4c1c-8d0f-af8b8adb9a4d.jpg)

![IMG_20230409_121901.jpg](https://user-images.githubusercontent.com/59944300/230758788-f3681074-0145-41d6-bf05-b039fad6918d.jpg)

**Comment by sk22** [comment]
![settings: behavior → show interaction counts](https://user-images.githubusercontent.com/6217438/230762747-8466c8a8-569d-4f11-9d94-2aad3f95f5b7.png)

there, that
