### ISSUE TITLE
Consider using FediNuke for the baseline blocklist instead

### ISSUE THREAD

**Issue by girlbossceo** [sk22/megalodon#511]
While greyhat-academy's list doesn't have any issues on its own, it hasn't been updated in quite a while and lacks some more nazi/fash/bigoted instances: https://seirdy.one/pb/FediNuke.txt

This list has zero-question bans that anyone can just look at the instance for 2 seconds and see that it's a highly toxic instance that Seirdy has vetted himself. Hell you might even be able to just Google the instance domain name and get your reason. Lots of fediadmins suggest new admins to use this list as a *baseline*, bare minimum blocklist, and expand your list gradually.

Using this would also reduce the code complexity on trying to parse the unusual TSV format, whereas this is a simple banlist with only domains and nothing else separated by newlines.

**Comment by sk22** [comment]
thank you!

**Comment by Taullo** [comment]
I'm fine with blocking actual CSAM, nazis, hate speech, harassment, etc. but I'm not entirely sure why fictional kink content needs to be on that list too. It blocks aethy.com even though the only thing we host is legal "taboo" art and we actually fight against abusive content. Can this be reevaluated? Thanks.
