### ISSUE TITLE
no video player visible if instance media misbehaves

### ISSUE THREAD

**Issue by selfisekai** [sk22/megalodon#517]
**Describe the bug**

fetching a thumbnail for video fails (that's a server problem) and no player shows up for the post, as if there was no video attached

**To reproduce**

1. Navigate to https://social.hackerspace.pl/@elia@donotsta.re/110379614449245316 (must be fetched from hackerspace.pl to repro, API url: https://social.hackerspace.pl/api/v1/statuses/110379614449245316)
2. nvidia experience

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
(Please test using the respective `upstream-xxxxxx.apk` provided in [Releases](https://github.com/sk22/megalodon/releases) or at least using the current Mastodon version from the Play Store)

not checked

> In case it does, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Megalodon, feel free to still create this issue!

**Screenshots and screen recordings**

![41437.png](https://github.com/sk22/megalodon/assets/11798442/62c8994c-2678-4f27-986e-20b221292ad7)

**Version**

Megalodon version: 1.2.0+fork.83-play

**Crash log**

n/a

**Comment by sk22** [comment]
i plan to work around this in #493

**Comment by sk22** [comment]
![Screenshot_20230527-011415_Megalodon](https://github.com/sk22/megalodon/assets/6217438/48f9e35a-7efe-4b39-8315-37fd7697e822)

will display like this in the next release

**Comment by sk22** [comment]
![Screenshot_20230527-012856_Megalodon](https://github.com/sk22/megalodon/assets/6217438/8c38075e-1422-4525-aa6e-9aee267d33bc)

will display like this in the next release!
