### ISSUE TITLE
Download all content of a user

### ISSUE THREAD

**Issue by Stu75e** [sk22/megalodon#519]
There is a need for an option that can receive the entire content of a user for educational content, including videos, etc.

Always when we want to receive the entire content of a user that we need, we have to select and download them one by one.
 ![Screenshot_20230520-174231_Mastodon](https://github.com/LucasGGamerM/moshidon/assets/133971463/46eb5aaf-4eb1-431f-a31c-a9fcfd9f9c76)

You can put this option here

**Comment by sk22** [comment]
assuming you mean downloading all attached media - no, i won't implement that as i can imagine many users wouldn't want people to download all their media.
(if you mean download one's own account (including all stored posts and media), that's something mastodon would have to implement, not a client app)
