### ISSUE TITLE
Megalodon crashes when searching an Akkoma instance

### ISSUE THREAD

**Issue by ymollard** [sk22/megalodon#523]
**Describe the bug**

Megalodon inherits from that upstream bug in the Mastodon Android app: the app crashes when typing at least 5 characters in the search bar from an account run by an Akkoma server.

**To reproduce**

1. In Megalodon, add a user account running on an Akkoma server. For example, use an account created on https://bdx.town/
3. Click the search button and type "aaaaa" 
4. The app starts searching...
5. It crashes after a few seconds 

**Does this happen in the official app?**

Yes

I have already created an issue on upstream there https://github.com/mastodon/mastodon-android/issues/468 that got no response.

**Server logs**

It may not help to much but on servers' side, the server answers search requests successfully. Here's a log captured when typing "barabtro" in the search bar from the official app, but I expect the same behaviour with Megalodon:
```
ip - - [17/Dec/2022:15:20:19 +0000] "GET /api/v2/search?q=barba&resolve=true HTTP/2.0" 200 18380 "-" "MastodonAndroid/1.1.4"
ip - - [17/Dec/2022:15:20:23 +0000] "GET /api/v2/search?q=barbatro&resolve=true HTTP/2.0" 200 1049 "-" "MastodonAndroid/1.1.4"
```

**Version**

Megalodon version: 1.2.0+fork.83-play (83)

**Comment by Jacocococo** [comment]
This is because it tries to load how much a hashtag has been used which is a feature Akkoma doesn't have. I have already created a fix in a fork that I plan on submitting very soon (with a few more Akkoma improvements)

**Comment by sk22** [comment]
> This is because it tries to load how much a hashtag has been used which is a feature Akkoma doesn't have. I have already created a fix in a fork that I plan on submitting very soon (with a few more Akkoma improvements)

ahhh, why do i always read comments after implementing stuff myself... well anyway, just fixed it (hope it doesn't cause any merge conflicts for you) and looking forward to your PR!!
