### ISSUE TITLE
Add option to move lists to home tab

### ISSUE THREAD

**Issue by muznyo** [sk22/megalodon#53]
It would be nice if feed had a lists tab instead of it being in explore tab

**Comment by sk22** [comment]
i agree, but i'm not yet sure how exactly could look... i don't necessarily want all lists to be in the home tab at all times, but maybe i can add a pinning lists feature, like on twitter? anyway, i'm not happy with the positioning of the "lists" tab anyway…

**Comment by muznyo** [comment]
maybe they could be in profile tab and in there u can choose which one you can pin to timeline tab

**Comment by sk22** [comment]
you mean in the three-dot menu? definitely an option i'm considering (and moving it out of the search/discover section entirely)

**Comment by muznyo** [comment]
no i meant in section where pinned, media, about, etc. is

but 3 dot menu could be nice too
