### ISSUE TITLE
Allow report forwarding to be disabled by default

### ISSUE THREAD

**Issue by Flightkick** [sk22/megalodon#565]
**Is your feature request related to a problem? Please describe.**
Some instances have stricter guidelines than others. When reporting accounts to our instance I more often report things that go against our specific server rules but are fine with others.
Currently I have to remember and disable report forwarding for every report.

**Describe the solution you'd like**
In the options I'd like to be able to configure the default setting for report forwarding to be opt-in or opt-out.

**Describe alternatives you've considered**
Keep disabling the forwarding manually every time or not use the report feature anymore but look for other moderation tools/processes.

**Additional context**
Related issue: https://github.com/sk22/megalodon/issues/205

**Comment by sk22** [comment]
hm, i could also flip the switch to be off by default..

**Comment by Flightkick** [comment]
Didn't expect such a quick update! Nice.

No clue which setting would be preferred by the majority so the setting would serve both scenarios. Thanks!
