### ISSUE TITLE
Infinitely unrolling announcement

### ISSUE THREAD

**Issue by jagotu** [sk22/megalodon#569]
**Describe the bug**

When opening the "announcements" section while there is an active announcement, the announcement gets repeated infinitely.

Just a theory: I suspect it's trying to unroll a "thread" of the announcement and just ends up fetching the same post over and over.

**To reproduce**

1. Login on an instance that has an announcement.
2. Click the announcements button  in the top bar.
3. Sse infinitely repeating post.

**Does this happen in the official app?**

Upstream doesn't seem to have the announcements section at all?

**Screenshots and screen recordings**

![Screenshot_20230611-233412](https://github.com/sk22/megalodon/assets/2465633/8153d72b-6e4f-4076-bd2f-3ccc75dfe899)

**Version**

Megalodon version: v1.2.3+fork.92

**Comment by sk22** [comment]
ah dang, thanks for noticing!

> Just a theory: I suspect it's trying to unroll a "thread" of the announcement and just ends up fetching the same post over and over.

nope, not quite; i recently added a feature that automatically invokes loading more posts when there are supposedly more available but the screen isn't filled yet: 4a0e4edef815869603e6e577d2a1637da1aeb43d
and the way i had handled the announcements page didn't play well that new feature

**Comment by jagotu** [comment]
Dang, you're fast! Thanks :)

I'm really happy with megalodon and will continue recommending it to everyone!

**Comment by sk22** [comment]
> Dang, you're fast! Thanks :)

i really wanted to have this fixed before going to sleep :D

> I'm really happy with megalodon and will continue recommending it to everyone!

thank you! :)
