### ISSUE TITLE
App crash on start

### ISSUE THREAD

**Issue by elln2** [sk22/megalodon#571]
**Describe the bug**

After updating to the latest app available on Google Play, I am no longer able to open the app. It immediately crashes when the icon is tapped.

**To reproduce**

1. Update to the latest version of the app on Google Play. I have 1.2.3+fork.93-play.
2. Tap the app icon from your launcher.
3. Experience crash.

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
(Please test using the respective `upstream-xxxxxx.apk` provided in [Releases](https://github.com/sk22/megalodon/releases) or at least using the current Mastodon version from the Play Store)

> No

**Screenshots and screen recordings**

Not much can be shown - the app immediately crashes on start. 

**Version**

Megalodon version: v1.2.3+fork.93-play

**Crash log**

I will try to obtain a crash log when able.

**Comment by kianga** [comment]
Same here, I also tried clearing the cache/storage and reinstalling. The phone is a Google Pixel 6a running Android 13.

**Comment by Fargascal** [comment]
Hello:

Same here, just updated to the latest version via Google Play on a Samsung Galaxy S23 ultra with android 13.

**Comment by sk22** [comment]
just pushed a new release; please let me know if i fixes it once you receive the update!

**Comment by Fargascal** [comment]
It works now!

**Comment by kianga** [comment]
The new version does not crash immediately after installation and I can log into my instance and even see the timeline once, but if I close the app and try to re-open it, it starts crashing again.

There is a toast notification at the bottom that's truncated, but the text I can see is:

```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to or...
```

**Comment by axeleroy** [comment]
Hello,

I just updated to version 1.2.3+fork.94-play (I guess it's the version you just pushed to the Play Store) and it still crashes on startup. My phone is a Pixel 6 Pro running Android 13.

**Comment by elln2** [comment]
> just pushed a new release; please let me know if i fixes it once you receive the update!

The update has resolved the problem for me. @sk22 I'll leave it up to you whether you'd like to resolve this issue - as original reporter I'm good now, but @axeleroy is still outstanding.

**Comment by axeleroy** [comment]
Version 95 fixed the issue for me, but it deleted the app data.

**Comment by kianga** [comment]
Version 95 also fixed the crashes for me. Thanks for the quick response!

**Comment by sk22** [comment]
> but it deleted the app data

okay, that's weird, but well, at least the crashes are gone. ^^'
