### ISSUE TITLE
Unable to return to 'recent searches' after searching

### ISSUE THREAD

**Issue by Flightkick** [sk22/megalodon#580]
**Describe the bug**

After searching for something, I am unable to get to the 'recent searches' overview.

**To reproduce**

1. Make sure you freshly start the app. (By swiping it off the recent apps list)
2. Go to the search tab, note it displays trending hashtags.
3. Click the search bar, note it shows recent searches.
4. Type some search query and confirm.
5. Now go back (either through the icon in the search bar or the native back feature on your phone).
6. Notice it shows trending hashtags again.
7. Press the search bar again. Even though there is no search query in the bar, it shows the latest results. Not recent searches. From here I have to do a fresh start of the app again in order to get the recent searches view to show.

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?
(Please test using the respective `upstream-xxxxxx.apk` provided in [Releases](https://github.com/sk22/megalodon/releases) or at least using the current Mastodon version from the Play Store)

> No / Yes

Not tested. Creating it here, if anyone who uses the official app experiences the same. Feel free to reference.

> In case it does, please consider filing an [upstream bug report](https://github.com/mastodon/mastodon-android/issues) instead.
> If this bug is seriously impacting your usage or you think I might want to try to fix it for Megalodon, feel free to still create this issue!

**Version**

Megalodon version: V1.2.3+fork.95-play
(May be nice if this would copy to the clipboard when you press the version label btw)

**Comment by sk22** [comment]
should be fixed in the newer pre-release versions (as the whole search experience is new)
