### ISSUE TITLE
Add ability to select app locale

### ISSUE THREAD

**Issue by fdmarcin** [sk22/megalodon#591]
**Is your feature request related to a problem? Please describe.**

Hi! I'd like to use your app in English, but my Android OS locale is set to another language. 

My OS language (Polish) feels awkward to me in the context of Mastodon, because most content I see there is in English. Also, not all the settings are localized.

**Describe the solution you'd like**

Consider adding an app setting to change the app UI language.

**Additional context** 

I'm currently using another app (Tusky) and are checking out Megalodon. This issue is a blocker for me moving clients.

**Comment by sk22** [comment]
might look into it, but in the mean time: if your android version supports it, you can change the app language in the app info: https://developer.android.com/guide/topics/resources/app-languages#app-language-settings

**Comment by fdmarcin** [comment]
@sk22 Thanks! 🤞 

Good to know about the Android setting finally being there. Unfortunately, I'm on Android 11 (sorry for not mentioning).
