### ISSUE TITLE
Add ability to switch between old UI and new Material 3 UI

### ISSUE THREAD

**Issue by d4f5409d** [sk22/megalodon#650]
**Is your feature request related to a problem? Please describe.**
The new Material 3 UI in the Mastodon app is just very bad. It looks like Google+ or some shitty Google application and I don't want my Mastodon experience to be like that. I liked the old look though.

**Describe the solution you'd like**
A toggle with we can switch back to the old UI while also having the new features and bug fixes

**Describe alternatives you've considered**
If applicable: a clear and concise description of any alternative solutions or features you've considered.
Not updating my apps, but that's a bit risky.

**Additional context**

**Comment by sk22** [comment]
nope, sorry. i can't and won't maintain basically two different apps at once.

**Comment by d4f5409d** [comment]
F

**Comment by sk22** [comment]
but hey, i'm doing everything to make sure the new app looks good, even with the new design! i'm certainly not applying the upstream design changes that i personally dislike

**Comment by sk22** [comment]
here's some screenshots of the progress so far. i personally really like it (it's even pinker than before, but again, there's themes)

![Screenshot_20230704-001425_Megalodon](https://github.com/sk22/megalodon/assets/6217438/a0848e2b-8ce1-41aa-b62b-680737f1227f)
![Screenshot_20230704-001436_Megalodon](https://github.com/sk22/megalodon/assets/6217438/3563d0d4-5f73-4e93-ac45-b0159b9856cc)
![Screenshot_20230704-001502_Megalodon](https://github.com/sk22/megalodon/assets/6217438/c01819f5-17b4-4aa6-814e-0cd9861fdb6a)

**Comment by d4f5409d** [comment]
Not too bad, better than the official one though. Thanks.

**Comment by sk22** [comment]
trying my best!
