### ISSUE TITLE
Three-dot icon merged with expand button

### ISSUE THREAD

**Issue by realpixelcode** [sk22/megalodon#651]
**Describe the bug**

The two icons are merged together.

**To reproduce**

No clue

**Does this happen in the official app?**

No.

**Screenshots and screen recordings**

![](https://github.com/sk22/megalodon/assets/52963327/d4b30130-6432-4627-a044-2247539bc7bc)

**Version**

Megalodon version: v1.2.3+fork.94

**Comment by sk22** [comment]
pretty sure that's fixed already (not yet released, probably). feel free to re-open this if it occurs again in the next version!
