### ISSUE TITLE
In-App updates download doesn't work

### ISSUE THREAD

**Issue by kevino-techie** [sk22/megalodon#67]
After getting an update notification in app settings. I click download option and a notification appears that app is  downloading something. But after a  minute the notification vanishes with no update apk being downloaded anywhere including the "downloads folder".
This issue had been present in earlier releases to as well as in Version 1.1.4+fork.45

tested on android v12

**Comment by sk22** [comment]
hm. well, the feature is from the official app (the feature just hasn't been released yet) and i've never really had this issue myself, so i wouldn't really know where to start trying to help you. maybe you can share a screen recording of what's happening? though i don't think i can help a lot with that right now :/

**Comment by karano-techie** [comment]
One possible cause i think there maybe cause the app doesn't ask for "files and media" permission for it to store the apk in my case. As in case of any browser where we are able to download any file ,it usually requires files and media access.
I don't know if it forms part of Appops permission or user has to grant it on start of the app.
![Screenshot_20221120-232743-437.png](https://user-images.githubusercontent.com/93819980/202918054-d9cb5bc6-54dc-4f9b-bc24-771792a114f4.png)

**Comment by sk22** [comment]
if this still occurs, please also try with the official app's github releases and maybe create an issue there, if applicable! otherwise, let me know

**Comment by kevino-techie** [comment]
Thanks ,auto-updating works now !
