### ISSUE TITLE
Hiding replies that are also a boost

### ISSUE THREAD

**Issue by spikethedog78** [sk22/megalodon#690]
Hiding replies from the timeline doesn't work if the reply is also boosted. 

This occurs when reading content from a Lemmy community, where all posts and replies are "boosted" by the community username.

**Comment by sk22** [comment]
not really a bug because it's intentional that boosts (including replies that are boosted) should still be visible when replies (non-boosted) are hidden in the home timeline. but yeah, an option to hide all replies sounds like a good idea
