### ISSUE TITLE
Do not post comments in the feed of subscribers

### ISSUE THREAD

**Issue by AlexValue** [sk22/megalodon#691]
I'm always frustrated when my feed is littered with minor comments (under other posts) of those I follow.

I want my comments to not be published in the megalodon by default in the feed of my subscribers. So that they have a different level of publicity (only for those who read the comments on the post).

Alternatively, a setting could be added that would allow me to hide the comments of people I follow from my feed. But if I read the comments under the post, then they should be available.

I ask that all comments on posts be set to the following privacy level:
![Screenshot_20230709-003311](https://github.com/sk22/megalodon/assets/107300467/ee4de521-7e82-41d9-9327-3298726f0105)

**Comment by sk22** [comment]
![Screenshot_20230709-020825_Moshidon Nightly](https://github.com/sk22/megalodon/assets/6217438/a0d4af07-ccd8-462b-bee9-8c4155ffee66)

disabling "show replies" should be what you want?

**Comment by sk22** [comment]
> disabling "show replies" should be what you want?

assuming it is, i'm now closing this issue. let me know if it's not that
