### ISSUE TITLE
Contrasting pill-shaped active indicator enable/disable in settings | m3 redesign

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#706]
Hey! I saw some of the screenshots in the replies to one of the closed issues. And when I look at those screenshots, I see "contrasting pill-shaped active indicator" (name copied from m3.material.io) in the navigation bar. So is it possible to add a way to disable this in the settings? It's not on fire. Only if you have the time and desire!

**Comment by sk22** [comment]
hm.. i mean, it can't hurt to include it, i guess
