### ISSUE TITLE
There are no icons on the avatar and hover says that you can change them (visual bug)

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#727]
**Describe the bug**
There are no icons on the avatar and hover that say you can change them. We can change them, but we don't know about it.

**To reproduce**

1. Open your account
2. Click on "Edit profile"

**Does this happen in the official app?**
In the latest upstream we have the same problem only for hover

**Screenshots and screen recordings**
![Screenshot_20230718-140348](https://github.com/sk22/megalodon/assets/62957728/e076ce4d-7c22-4bac-8dd0-ea3503a70a3b)

**Version**
Megalodon version: Megalodon v2.0.1+fork.96 (96)

**Comment by sk22** [comment]
ahhh ffs, i've fixed this like at least 3 times in the past; good to know it's broken again 💀 thanks for reporting!
