### ISSUE TITLE
Bio isn't hidden while scrolling 

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#728]
**Describe the bug**
Sometimes part of bio isn't hiden when I reading content on my profile page

**To reproduce**
It's hard to reproduce. Just open your profile page and try to catch it.

**Does this happen in the official app?**
No. They have another problem that makes it impossible to check.

**Screenshots and screen recordings**
GitHub won't let me add my video here so I'm adding the link to it below 

**Version**
Megalodon version: v1.2.0+fork.96

**Crash log**
I will try to create it later

**Comment by neilideal** [comment]
Video: https://app.skiff.com/file/bddc6fbb-0724-4cba-af8d-75f22542077d

**Comment by sk22** [comment]
i don't know how to view this video (apparently github is broken right now? uploading videos usually works for me...), but if it's just like scrolling up on the tabs bar (which reveals the metadata even if the posts aren't scrolled all the way to the top yet), then it's a won't-fix

**Comment by neilideal** [comment]
New link with video:
https://photos.app.goo.gl/S8EQZ7mTtdPeMnVj6

**Comment by sk22** [comment]
ah! this is probably closely related to #684

**Comment by neilideal** [comment]
It feels like I got the logs. Very interesting to me that this bug appears after creating a post
[mega_log_full.txt](https://github.com/sk22/megalodon/files/12130293/mega_log_full.txt)

**Comment by sk22** [comment]
no worries - i'll take a look at it when i have time. tho, i doubt logs will help me much - i mean it's not like i expect there to be any output because of an unexpected result. i'm assuming the content view somehow gets measured, idk, wrong..
