### ISSUE TITLE
Links to change profile information don't work

### ISSUE THREAD

**Issue by neilideal** [sk22/megalodon#730]
**Describe the bug**
Links to site in instance settings don't work

**To reproduce**
1. Go to Settings -> Instance
2. Click on "Profile Setup", "Posting Preferences", "Security Settings".
3. Browser doesn't open

**Does this happen in the official app?**
Does this issue also occur with the respective upstream release?
No, they don't have this functionality

**Screenshots and screen recordings**
https://github.com/sk22/megalodon/assets/62957728/53f9a214-1fe7-456e-a057-cecb2c2f7422

**Version**
Megalodon version: [e.g. v2.0.1+fork.96]

**Crash log**
[mega_log_full.txt](https://github.com/sk22/megalodon/files/12091946/mega_log_full.txt)

**Comment by sk22** [comment]
that's weird; it works for me..
do "open in browser" buttons work for you? (like in the three-dot menu in posts) because they use exactly the same method

**Comment by neilideal** [comment]
Now all of them works fine

**Comment by sk22** [comment]
🤔

**Comment by neilideal** [comment]
There was an update... Maybe you fixed it earlier?

**Comment by sk22** [comment]
don't think i did.. maybe your phone was somehow unable to open URLs? idk,

**Comment by neilideal** [comment]
But before the update, such links worked. After the update came, they stopped. Then another update and everything is fine again. I should note that this only applied to links of the type found in the settings. In all other cases, everything worked fine. Also, this problem did not occur in other applications, which excludes the possibility that it was some kind of problem on my side...

**Comment by sk22** [comment]
that's.. weird. i'll close this issue then - please do re-open it (or like, let me know) if encountered again

**Comment by neilideal** [comment]
Ok
