### ISSUE TITLE
Setting to change that video stops music playback

### ISSUE THREAD

**Issue by SavoVuksan** [sk22/megalodon#733]
I really like the app and use it quite often but I kinda get annoyed by the behavior that when I start a video on the app the app stops my music playback. I would like to have the option to change this behaviour that I could listen to music while watching videos.

**Describe the solution you'd like**
Basically an extra property in the settings that enables me to switch between these modes. Like: Stop music playback when watching videos Yes/No

**Comment by FineFindus** [comment]
I think I have a working implementation, but can't test it, as I did not find any media with sound. Could you please include examples?

**Comment by SavoVuksan** [comment]
I actually already made an implementation but didn't have the time to create an PR. But if you like to try yours. To test it I just opened spotify and started playing music and then I started a video in mastodon. The music of spotify should duck and as soon as the video is closed again the music should play at full volume again.
