### ISSUE TITLE
Megalodon crashes when opening a certain post

### ISSUE THREAD

**Issue by ExperiencersInternational** [sk22/megalodon#736]
**Describe the bug**

Megalodon crashes when opening a post on Firefish by someone on the same server who has boosted their own post?

I can't really describe and I tried to reproduce this by making a post on Calckey, boosting it and then opening it on Megalodon with my Firefish account, but it didn't have any issues loading it.

**Screenshots and screen recordings**

https://youtube.com/shorts/BD8GmSGFw4I?feature=share

**Version**

Megalodon version: v1.2.3+fork.94

**Comment by ExperiencersInternational** [comment]
I think this might just be potentially someone deleting it, that's all.

Probably was dumb to file a bug report

**Comment by sk22** [comment]
well, megalodon shouldn't crash for deleted posts either.. you don't happen to have a crash log, do you?

**Comment by ExperiencersInternational** [comment]
No, I didn't record a crash log, sorry.
