### ISSUE TITLE
Only collapse posts that exceed the instance's character limit

### ISSUE THREAD

**Issue by d4f5409d** [sk22/megalodon#744]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when Megalodon collapses posts that aren't exceeding 500 characters (which is my instance's limit for posts)

**Describe the solution you'd like**
I already described in the title

**Describe alternatives you've considered**
If applicable: a clear and concise description of any alternative solutions or features you've considered.
*

**Additional context**

**Comment by sk22** [comment]
nope, for two reasons: many instances' character limits are quite high, and the current implementation is based on pixels, not on character count

**Comment by d4f5409d** [comment]
> nope, for two reasons: many instances' character limits are quite high, and the current implementation is based on pixels, not on character count

I mean Megalodon should pay attention to the home instance of the user that's logged in. That's more sense to use that for collapsing toots or not.

**Comment by sk22** [comment]
an instance i'm on has a character limit of 151000

**Comment by d4f5409d** [comment]
Then we should be able to customize the limit locally?

**Comment by d4f5409d** [comment]
> an instance i'm on has a character limit of 151000
> 
> On August 29, 2023 6:57:44 AM GMT+02:00, d4f5409d ***@***.***> wrote:
> >> nope, for two reasons: many instances' character limits are quite high, and the current implementation is based on pixels, not on character count
> >
> >I mean Megalodon should pay attention to the home instance of the user that's logged in. That's more sense to use that for collapsing toots or not.
> >
> >-- 
> >Reply to this email directly or view it on GitHub:
> >https://github.com/sk22/megalodon/issues/744#issuecomment-1696766490
> >You are receiving this because you modified the open/close state.
> >
> >Message ID: ***@***.***>

But that's pretty much the instance's or your fault for choosing that instance 🤷‍♂️
