### ISSUE TITLE
Redirect loop on login

### ISSUE THREAD

**Issue by rafal06** [sk22/megalodon#766]
**Describe the bug**

When trying to log in, Mastodon goes to a redirect loop from the authorization screen

**To reproduce**

1. Enter the instance domain and click next
2. Mastodon login screen opens in a web view. Enter credentials and 2FA code if configured.
3. Mastodon authorization screen shows up
4. Click 'Authorize'

**Does this happen in the official app?**

Does this issue also occur with the respective upstream release?

> No, tested with master (mastodon/mastodon-android@c3da15552eb45725713d221ba5b719deba85ae09; compiled from source)

**Screenshots and screen recordings**

https://github.com/sk22/megalodon/assets/70489677/f065e22d-7518-4f0d-a47a-d4e1876e4987

**Version**

Megalodon version: compiled from main (6054a3d65c78daf98e32486128b9507d34abfe40)

**Crash log**

[megalodon2.log](https://github.com/sk22/megalodon/files/12407708/megalodon2.log)

**Comment by rafal06** [comment]
I tried again with the latest commit from main (937304f27bbaf73f1221067e5b53f843b6dcca89), and it works now. Closing this issue, then.

**Comment by sk22** [comment]
> I tried again with the latest commit from main ([937304f](https://github.com/sk22/megalodon/commit/937304f27bbaf73f1221067e5b53f843b6dcca89)), and it works now. Closing this issue, then.

oh weird, i didn't change anything about authentications..

**Comment by rafal06** [comment]
> > I tried again with the latest commit from main ([937304f](https://github.com/sk22/megalodon/commit/937304f27bbaf73f1221067e5b53f843b6dcca89)), and it works now. Closing this issue, then.
> 
> oh weird, i didn't change anything about authentications..

Yeah, idk why it started working
