### ISSUE TITLE
latest upgrade reset Mastodos

### ISSUE THREAD

**Issue by lichingyun** [sk22/megalodon#77]
I am using  Mastodos (fork 45) and the upgrade to fork 46 reset it.
I have 4 account to 4 different istances and after the upgrade I see the first screen of Mastodos in wich I need to choice the instance to log in

I am sorry but don't have the logcat
I am using a Xiaomi Redmi Note 5 Whyred with Android 12.1

**Comment by sk22** [comment]
Yep, sorry for the inconvenience – that's because of #72 (I set the latest release to be "debuggable"). I since set it to be not debuggable, so it will happen again with the next release. Sorry!

**Comment by lichingyun** [comment]
No problem Samuel 🙏 thanks for your kindly answer, I am not a developer, I am only a user

21 nov 2022 17:51:05 sk22 ***@***.***>:
