### ISSUE TITLE
UnifiedPush: Toggle untoggles itself

### ISSUE THREAD

**Issue by Sir-Photch** [sk22/megalodon#770]
**Describe the bug**

On the latest pre-release, enabling UnifiedPush does not keep its "enabled" status upon closing the app in the app overview and opening it up again, when viewing the notification settings screen.
The entry in ntfy stays though. Is this just a cosmetical issue?

**To reproduce**

1. Enable UnifiedPush
2. Exit the app
3. Close it in the app drawer
4. Open it back up, view the UnifiedPush setting

**Does this happen in the official app?**

Not applicable

**Version**

Megalodon version: [e.g. v2.0.3+fork.98]

**Comment by sk22** [comment]
as it seems, the unifiedpush settings item didn't work when the switch itself is being pressed - but it does work when pressing the text. so, until the next (pre-) release: don't touch the switch :')

**Comment by Sir-Photch** [comment]
Haha, I see. I'll make sure not to come anywhere close!
