### ISSUE TITLE
Problems with unifiedpush

### ISSUE THREAD

**Issue by p1gp1g** [sk22/megalodon#779]
**Describe the bug**

I've installed [v2.0.3+fork.98](https://github.com/sk22/megalodon/releases/tag/v2.0.3%2Bfork.98) which is very probably not a F-Droid flavor. I've seen some issues (pretty easy to fix)

1. Crash while (un)registering 

(Un)registering a new unifiedpush distributor crash the app.  The issue happen when `account.getPushSubscriptionManager().registerAccountForPush(null);` is called [here](https://github.com/sk22/megalodon/blob/main/mastodon/src/main/java/org/joinmastodon/android/UnifiedPushNotificationReceiver.java#L32). It should probably be `account.getPushSubscriptionManager().registerAccountForPush(null, endpoint);`

I think that all `registerAccountForPush(null)` should be in a try/catch block.

2. The app does not register

That, is probably because `registerAccountForPush(null)` is called instead of `registerAccountForPush(null, endpoint)`. Or because of the crash.

3. The right account is not picked

Currently, the account registering is [the last active instead of the one linked to the instance](https://github.com/sk22/megalodon/blob/main/mastodon/src/main/java/org/joinmastodon/android/UnifiedPushNotificationReceiver.java#L30) 

I think it should be `AccountSessionManager.getInstance().getAccount(instance);` (in a try/catch block) instead of `AccountSessionManager.getInstance().getLastActiveAccount();`

**Version**

Megalodon version: v2.0.3+fork.98

**Crash log**

```
08-28 12:53:08.573 31272 31272 D UnifiedPushNotificationReceiver: onNewEndpoint: New Endpoint https://REDACTED for REDACTED_119856
08-28 12:53:08.574 31272 31272 D AndroidRuntime: Shutting down VM
--------- beginning of crash
08-28 12:53:08.576 31272 31272 E AndroidRuntime: FATAL EXCEPTION: main
08-28 12:53:08.576 31272 31272 E AndroidRuntime: Process: org.joinmastodon.android.sk, PID: 31272
08-28 12:53:08.576 31272 31272 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver org.joinmastodon.android.UnifiedPushNotificationReceiver: java.lang.IllegalStateException: No device push token available
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4326)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2159)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7940)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at com.android.internal.os.ExecInit.main(ExecInit.java:49)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
08-28 12:53:08.576 31272 31272 E AndroidRuntime: Caused by: java.lang.IllegalStateException: No device push token available
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at org.joinmastodon.android.api.PushSubscriptionManager.registerAccountForPush(SourceFile:532)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at org.joinmastodon.android.UnifiedPushNotificationReceiver.onNewEndpoint(SourceFile:32)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at org.unifiedpush.android.connector.MessagingReceiver.onReceive(SourceFile:30)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4317)
08-28 12:53:08.576 31272 31272 E AndroidRuntime:        ... 11 more
```

**PS**

That's cool to see UnifiedPush support for this app :)

**Comment by FineFindus** [comment]
Thanks for the report, I'll look into it. Is this a completely fresh installation of the app?

> I think that all registerAccountForPush(null) should be in a try/catch block.

There's no need, unless something went severely wrong, the method should never fail. 

> (Un)registering a new unifiedpush distributor crash the app. The issue happen when account.getPushSubscriptionManager().registerAccountForPush(null); is called [here](https://github.com/sk22/megalodon/blob/main/mastodon/src/main/java/org/joinmastodon/android/UnifiedPushNotificationReceiver.java#L32). It should probably be account.getPushSubscriptionManager().registerAccountForPush(null, endpoint);

The `registerAccountForPush(null)` is used to re-register the device to FCM push messages, when disabling Unified Push.
I can't remember why I didn't use the endpoint, it's quite possible that I accidentally replace it, will look into it.

> Currently, the account registering is [the last active instead of the one linked to the instance](https://github.com/sk22/megalodon/blob/main/mastodon/src/main/java/org/joinmastodon/android/UnifiedPushNotificationReceiver.java#L30)

Good catch, I forgot, the account is available at the point. Feel free to create a pr for it, if you want. The try-catch should not be necessary, as the requested account should always be available (unless the user deletes it, but then they can't enable UP)

The crash is caused by the device token being unavailable, which is obtained when registering to FCM. Not quite sure yet, why it crashes, it should be checked if the token is available before trying to register.

**Comment by FineFindus** [comment]
Also, mind pinging/mentioning me for future Unified Push issues, I nearly missed this :)

**Comment by p1gp1g** [comment]
> The crash is caused by the device token being unavailable, which is obtained when registering to FCM. Not quite sure yet, why it crashes, it should be checked if the token is available before trying to register.

That's a fresh install, and I don't have any GApps. That's probably why it crashes.

I suggest a try catch for these kind of issues but you can also change [the throw ](https://github.com/sk22/megalodon/blob/main/mastodon/src/main/java/org/joinmastodon/android/api/PushSubscriptionManager.java#L132), probably introduced in mastodon, because the registration always happen after the device get a token with FCM (when there is no UnifiedPush)

**Comment by sk22** [comment]
> > The crash is caused by the device token being unavailable, which is obtained when registering to FCM. Not quite sure yet, why it crashes, it should be checked if the token is available before trying to register.
> 
> That's a fresh install, and I don't have any GApps. That's probably why it crashes.
> 
> I suggest a try catch for these kind of issues but you can also change [the throw ](https://github.com/sk22/megalodon/blob/main/mastodon/src/main/java/org/joinmastodon/android/api/PushSubscriptionManager.java#L132), probably introduced in mastodon, because the registration always happen after the device get a token with FCM (when there is no UnifiedPush)

that makes sense, i think!

how about just returning in case it's an f-droid build or the device token is empty? idk about the rest of the UnifiedPush implementation in megalodon; maybe there's a more elegant way

```diff
diff --git a/mastodon/src/main/java/org/joinmastodon/android/api/PushSubscriptionManager.java b/mastodon/src/main/java/org/joinmastodon/android/api/PushSubscriptionManager.java
--- a/mastodon/src/main/java/org/joinmastodon/android/api/PushSubscriptionManager.java	(revision 83e84836b5a83c2e88c83a0001bb5db17354c807)
+++ b/mastodon/src/main/java/org/joinmastodon/android/api/PushSubscriptionManager.java	(date 1693255832308)
@@ -125,11 +125,9 @@
 		// this function is used for registering push notifications using FCM
 		// to avoid NonFreeNet in F-Droid, this registration is disabled in it
 		// see https://github.com/LucasGGamerM/moshidon/issues/206 for more context
-		if(BuildConfig.BUILD_TYPE.equals("fdroidRelease"))
+		if(BuildConfig.BUILD_TYPE.equals("fdroidRelease") || TextUtils.isEmpty(deviceToken))
 			return;
-
-		if(TextUtils.isEmpty(deviceToken))
-			throw new IllegalStateException("No device push token available");
+		
 		String endpoint = "https://app.joinmastodon.org/relay-to/fcm/"+deviceToken+"/"+accountID;
 		registerAccountForPush(subscription, endpoint);
 	}
```

**Comment by p1gp1g** [comment]
This change to fix the crash makes sens IMO.
