### ISSUE TITLE
Status interaction values not visible on small screen devices

### ISSUE THREAD

**Issue by FineFindus** [sk22/megalodon#787]
**Describe the bug**

The number of boosts and favorites is not fully displayed on smaller devices, whereas the official app displays them correctly. This is due to the slightly larger icons used in Megalodon compared to upstream.

**To reproduce**

1. Enable Show status interactions
2. Visit a post with lots of boosts (e.g. https://floss.social/@gnome/110894912595729593)
3. Notice how the status interactions are not fully displayed

**Does this happen in the official app?**
No

**Screenshots and screen recordings**
![SCreenshot of a post with lots of boosts](https://github.com/sk22/megalodon/assets/63370021/9539cf9b-1803-4688-be2b-436a60ef2a59)

**Version**

Megalodon version: v2.0.3+fork.98

**Comment by sk22** [comment]
i'm not sure i can really fix this without breaking the layout. i have however improved it somewhat

* icons don't scale with the text anymore (if only the "text size" option is changed, the icons no longer scale, too. they probably shouldn't anyway - that's what the "display size" option is for)
* ~i no longer align the reply button with post avatars at all cost. with "normal" scaling, the reply icon will still be horizontally centered to avatars. changing the "11sp" margin (around the footer) to "11dp" gives the icons more horizontal space to spread.~
* nevermind the above; the buttons are now aligned with the text and other ui elements
* i've changed the (minimum; will be extended by the counters) width of the buttons to 48dp (used to be 56dp). this is smaller, which i don't like, but i think it's big enough

now this won't fix this in every case, but i believe i gave the texts considerably more space

**Comment by sk22** [comment]
closed with https://github.com/sk22/megalodon/commit/7b263800a65024861f8313260a1bdf47adebd45a
