### ISSUE TITLE
Muted Words 

### ISSUE THREAD

**Issue by evanpeterjones** [sk22/megalodon#80]
Would love a word filter to apply to list views. So posts that include a phrase anywhere if them are automatically filtered out. the way twitter implements "muted words"

**Comment by sk22** [comment]
You can already set muted words in your instance's web UI! (Preferences → Filters) These settings should also automatically apply for any Mastodon app.

![image](https://user-images.githubusercontent.com/6217438/203180314-aac3eddb-6c1b-4447-85a5-e55b7dd69ca6.png)

So, is this what you were hoping for?

And of course, I could add a section in the settings where you can configure this directly in the app, but there's quite a lot missing there, so… I'm not gonna bother doing that, at least for now.
