### ISSUE TITLE
"Load additional posts" doesn't obey "hide boosts" and "hide replies"

### ISSUE THREAD

**Issue by jcrabapple** [sk22/megalodon#813]
**Describe the bug**

"Load additional posts" doesn't obey "hide boosts" and "hide replies". It shows boosts and replies even though they are supposed to be hidden. 

**Version**

Megalodon version: [e.g. v1.1.4+fork.#]

**Comment by sk22** [comment]
should be fixed now. please re-open if i'm wrong!
