### ISSUE TITLE
Emoji reaction add button maintains state after fragment reload 

### ISSUE THREAD

**Issue by LucasGGamerM** [sk22/megalodon#830]
When the add emoji button is toggled, and you proceed to reload the fragment without untoggling the add emoji button, the emoji keyboard goes away while the emoji button toggled state is maintained. This is not desirable behavior

**Comment by neilideal** [comment]
What if you don't add a new button, but make a "Facebook Like" button - when you click on the "favorite" button, a popup bar with your favorite emoji and a "+" icon will appear to open the entire emoji list. This will only work for instances that support emoji

**Comment by sk22** [comment]
> What if you don't add a new button, but make a "Facebook Like" button - when you click on the "favorite" button, a popup bar with your favorite emoji and a "+" icon will appear to open the entire emoji list. This will only work for instances that support emoji

i thought about a long-click triggering some kind of pop-up, but i neither did i know how best to design and implement that, nor do i want to change the current behavior of the fav button
