### ISSUE TITLE
"Filters" duplicated in Settings menu

### ISSUE THREAD

**Issue by DBendit** [sk22/megalodon#850]
**Describe the bug**

There are two entries for Filters in Settings. Both work, but it's weird that there's two of them.

**To reproduce**

1. Go to Settings
2. See that there's two entries for Filters, each with a different icon

**Does this happen in the official app?**

> No

**Screenshots and screen recordings**

If applicable, add screenshots (and screen recordings, if possible) to help explain your problem.

![photo1696842139](https://github.com/sk22/megalodon/assets/242696/58ce5663-6f50-42fb-be93-49ce25e36679)

**Version**

Megalodon version: v2.1.6+fork.102 (102)

**Crash log**

N/A

**Comment by DBendit** [comment]
Apparently only one gets shown for Akkoma: https://github.com/sk22/megalodon/blob/main/mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsMainFragment.java#L68

**Comment by sk22** [comment]
> Apparently only one gets shown for Akkoma: https://github.com/sk22/megalodon/blob/main/mastodon/src/main/java/org/joinmastodon/android/fragments/settings/SettingsMainFragment.java#L68

that was because i added the instance-is-akkoma check to megalodon; upstream doesn't do that. somehow, when merging the upstream changes, i accidentally merged the original filter settings item back (without the if-condition)
