### ISSUE TITLE
Changing themes per account is too painful

### ISSUE THREAD

**Issue by LucasGGamerM** [sk22/megalodon#853]
For someone with 5+ accounts, its hard to have to manually change it all one at a time.

Could there be an option to change themes globally again?

**Comment by sk22** [comment]
i think a good option would be having an "apply for all accounts" button next to "save" and "cancel"

**Comment by LucasGGamerM** [comment]
Maybe. That could be a compromise. But maybe saving for all accounts should be the default behavior, as its how it is on most softwaree

**Comment by sk22** [comment]
fair point.. but i could imagine that when "apply for current account" is the secondary option and "save" applies it for all, it might be pretty frustrating if pressed accidentally

**Comment by LucasGGamerM** [comment]
Maybe... We will see what can be done in terms of UI

**Comment by sk22** [comment]
okay, so.. this implementation might be somewhat confusing, but functionally, i think it's fine. (especially considering i didn't add a whole separate setting) maybe the "default" wording can be improved, but i don't really know how. let me know if you have any ideas!
