### ISSUE TITLE
Unnecessarily localizing hearted like option 

### ISSUE THREAD

**Issue by LucasGGamerM** [sk22/megalodon#857]
I feel like this setting should belong in the GlobalUserPreferences, as its an otherwise 'normal' setting. This is one of those cases where it gets unnecessarily complicated to change this setting globally for 7 different accounts (I have most of them in different instances and backends, so I can test more easily).

**Comment by sk22** [comment]
agreed

**Comment by LucasGGamerM** [comment]
![image](https://github.com/sk22/megalodon/assets/71328265/67cbcdaa-2a24-4722-8c53-554ed6d5d40c)

I had a good laugh! 

I should probably do some humor commit messages from time to time

**Comment by sk22** [comment]
:D

(i don't think so! if you had no sense of humor, you probably wouldn't have found my commit message funny ^^)
