### ISSUE TITLE
Crop images to a defined max height 

### ISSUE THREAD

**Issue by snaggen** [sk22/megalodon#884]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when 

Images and video in portrait aspect ratio, can take up the whole mobile screen or more. By doing that, they are basically stealing attention from everything else. 

**Describe the solution you'd like**

I'd like to have an option to crop images and video thumbs that take up more than 50% of the screen, or possibly some configurable percentage.

**Additional context**

This guy, who I have no interest in, do not deserve to steal all focus from real posts.
![Screenshot_20231020-180037_Trebuchet.png](https://github.com/sk22/megalodon/assets/6420639/8b01e250-dd8f-47cd-86e1-8e888803fa8e)

**Comment by sk22** [comment]
not configurable, but media will have a maximum height in the next release
