### ISSUE TITLE
Language selector

### ISSUE THREAD

**Issue by sk22** [sk22/megalodon#9]

**Comment by kescherCode** [comment]
Putting a screenshot of the glitch-soc web version here for reference.
![The compose section on the glitch-soc Mastodon fork post composing interface. There's a language selector button saying "EN" that has been clicked to reveal a search bar as well as a lot of other languages than English, such as German, Afar, Abhkaz, Avestan and others)](https://user-images.githubusercontent.com/23276523/170845867-2b233adf-bd8f-4502-ae82-cb89bc2c0f9e.png)

Something to implement could be that whatever will show the list of languages could sort itself by languages recently used, in addition to the mere alphabetical order. That would match the behaviour seen in the screenshot.

**Comment by sk22** [comment]
will do, thanks for the hint!
