### ISSUE TITLE
The ability to choose your own accent color

### ISSUE THREAD

**Issue by neilcrownis** [sk22/megalodon#90]
It would be nice to add the ability for users to choose a color scheme for the application. For starters, you could make options such as blue (the original color), purple (the official service color), pink (the color of the app), and a monochrome theme

**Comment by sk22** [comment]
so, technically this would be a duplicate, but i just closed the other issue, so… not marking this as a duplicate :D
i like the idea – especially with the proposed options – but i won't implement this for now. 
if anyone else wants to work in this, please do and submit a pull request! i think implementing this should also not be too complicated – there would need to be new styles for the respective themes and a new option in the settings. since there's already a theme picker in the settings, it should be a matter of extending the existing theming logics. the additional accent colors/themes could be a dropdown below (or above) the “true black mode” setting.

**Comment by LucasGGamerM** [comment]
Adding a toggle for the original mastodon colors and app icon would be quite great

**Comment by neilideal** [comment]
![Screenshot_20221126-094610.png](https://user-images.githubusercontent.com/62957728/204076129-7cc4635b-a33e-4e1a-8a37-1615a0bd481a.png)
This is what it looks like in Fritter. In terms of location, it does not contradict the logic that is used

**Comment by LucasGGamerM** [comment]
I managed to build megalodon using the original mastodon color scheme without any major modifications to the colors.xml file. I will be working on making it a toggle for the original mastodon color scheme and the megalodon color scheme. It would also be much appreciated if @sk22 could share the app icon project file, so that i could also change its colors based on the state of the toggle.

**Comment by LucasGGamerM** [comment]
The implementation of this is quite janky for now, and it almost doesnt work. But i have got an early alpha ready. If anyone is interested, i will post more updates on the situation here.

**Comment by LucasGGamerM** [comment]
I have scrapped my pretty bad implementation, i will instead work on supporting material you colors.

**Comment by neilideal** [comment]
> The implementation of this is quite janky for now, and it almost doesnt work. But i have got an early alpha ready. If anyone is interested, i will post more updates on the situation here.

It's interesting, at least to me! And I read the comment below about the idea with material you. It's even tougher!

**Comment by LucasGGamerM** [comment]
I have some good news, i managed to integrate the switch to mastodon original colors, and i am scrapping the material you color thing (too much work for what its worth). Its now implemented in a much more maintainable and clean way. I will create a pull request with the code later this afternoon. It will be awesome :D

**Comment by LucasGGamerM** [comment]
Alright guys, the code is ready and finally its bugless. I am filing the pull request.

**Comment by LucasGGamerM** [comment]
Ok, there were some bugs i didnt find, but they are all now fixed. I am waiting on the approval of the pull request.

**Comment by LucasGGamerM** [comment]
> so, technically this would be a duplicate, but i just closed the other issue, so… not marking this as a duplicate :D i like the idea – especially with the proposed options – but i won't implement this for now. if anyone else wants to work in this, please do and submit a pull request! i think implementing this should also not be too complicated – there would need to be new styles for the respective themes and a new option in the settings. since there's already a theme picker in the settings, it should be a matter of extending the existing theming logics. the additional accent colors/themes could be a dropdown below (or above) the “true black mode” setting.

I will also work on implementing a greenish theme and the drop down menu for such themes. But this is not for today

**Comment by neilideal** [comment]
> > so, technically this would be a duplicate, but i just closed the other issue, so… not marking this as a duplicate :D i like the idea – especially with the proposed options – but i won't implement this for now. if anyone else wants to work in this, please do and submit a pull request! i think implementing this should also not be too complicated – there would need to be new styles for the respective themes and a new option in the settings. since there's already a theme picker in the settings, it should be a matter of extending the existing theming logics. the additional accent colors/themes could be a dropdown below (or above) the “true black mode” setting.
> 
> I will also work on implementing a greenish theme and the drop down menu for such themes. But this is not for today

If we want to attract an audience that is leaving Twitter and looking for an app with a beautiful interface and actively developing functionality, then we can add those colors that were in Twitter itself, viz:
Blue, pink, orange, yellow, green, purple.

**Comment by LucasGGamerM** [comment]
Creating the themes themselves isnt hard. I myself did it in less than a few minutes. But implementing the ui for them is *not yet* feasible for me. Test week is coming, and i have to study. But besides, i will setup some time to actually put some theming options  later

**Comment by sk22** [comment]
> Creating the themes themselves isnt hard. I myself did it in less than a few minutes.

Tbh, I disagree. Like – themes are so easy to mess up, imo. Not only by making them, well, not pretty in the first place, but also by meeting accessibility requirements. For example, the official app, for example, has previously (after switching from blue to purple) had quite some awful contrasts – see https://github.com/mastodon/mastodon-android/issues/217#issuecomment-1184484599.
(Contrasts can be checked with tools like https://webaim.org/resources/contrastchecker)

**Comment by LucasGGamerM** [comment]
I did not make myself clear. I meant choosing primary colors. In my pull request, I reimplemented the purpleish mastodon theme by parenting the already existing theme. Therefore, all that changed were the accent colors, which is exactly what we want.

**Comment by LucasGGamerM** [comment]
Implementing material you colors is seeming to be quite the issue. Specially because whenever I include the required libraries, the app fails to load, saying that there are many duplicate classes. This is quite not good

**Comment by LucasGGamerM** [comment]
Ok, I think I have quite the functional thing here. 4 color options, green, pink, purple and blue. And a nice coherent design that doesn't feel out of place. I think it's ready for release at this point 
![Screenshot_20221203-222951](https://user-images.githubusercontent.com/71328265/205469988-3645d280-5cfa-4e7b-9245-cc3add36809a.png)

**Comment by LucasGGamerM** [comment]
Imma add orange and yellow later too

**Comment by LucasGGamerM** [comment]
Ok guys, its basically finished. The fab, the publish button, the trueblack theme, everything is just set right. Hopefully @sk22 aproves the pull request. When he does so, this issue will be closed. I think that's it

**Comment by LucasGGamerM** [comment]
I found a few minor inconsistencies, imma fix them tomorrow

**Comment by sk22** [comment]
> Ok guys, its basically finished. The fab, the publish button, the trueblack theme, everything is just set right. Hopefully @sk22 aproves the pull request. When he does so, this issue will be closed. I think that's it

I'll look over the code when I find time and maybe make some adjustments, but I definitely want to merge the PR soon. The screenshots look really good, thanks a lot!

**Comment by LucasGGamerM** [comment]
Hey, so, I implemented a Material you color theme option on https://github.com/LucasGGamerM/moshidon/releases/tag/1.1.4%2Bfork.62.moshinda . Github was a little worky and didnt allow me to create a pull request. But its done and its there
