### ISSUE TITLE
Add a shortcut to lists in the home

### ISSUE THREAD

**Issue by Krusty27** [sk22/megalodon#91]
#### The problem
As of now, lists are a bit far to reach and, if someone uses them as the main way of navigating Mastodon, a faster way to reach lists could be useful.

#### The proposal
Add a button in the home that opens the list of lists, above or near the pencil button.

![image](https://user-images.githubusercontent.com/28927643/203553849-8b71691c-82b3-4aa5-9506-2d7d78a5a5a9.png)

**Comment by neilideal** [comment]
I don't know how hard it is to implement, but it seems to me that placing such an element to the left of the logo would make the panel with it more symmetrical. I've always thought that ideally you would place a choice between feeds (local, global, yours) and keep the lists in the same dropdown menu along with them.
This is partly inspired by the official client for iOS, with a settings button on the left and a content creation button on the right

![image](https://user-images.githubusercontent.com/62957728/203557434-937ab494-e2c5-4dcc-a015-24a6542f9a45.png)

**Comment by Krusty27** [comment]
Yes that could be good too, anywhere is fine!

**Comment by sk22** [comment]
well i won't add a floating action button, that'd be semantically wrong imo. but having the lists in the header bar's corner is something i've considered before. i think i might do it like this!
