### ISSUE TITLE
Option to revert to old material 2 UI

### ISSUE THREAD

**Issue by i-lost-my-bagel** [sk22/megalodon#912]
**Is your feature request related to a problem? Please describe.**
My app updated today and it just looks so much worse now. The unnecessary rounding and text labels on the buttons on the bottom.

**Describe the solution you'd like**
Option to switch to the old material 2 UI

**Comment by neilideal** [comment]
You're able to deactivate pillshaped selection and text labels in app settings

**Comment by sk22** [comment]
> Option to switch to the old material 2 UI

sorry, can't do that. a _lot_ has changed in the meantime, introducing lots of incompatibilities between the old version and the new one. adding an option to revert to the old theme would mean re-implementing the old styles from the ground up, and that's not something i want to do.
