### ISSUE TITLE
Discrepancy between selected and displayed post schedule time due to DST correction.

### ISSUE THREAD

**Issue by Flightkick** [sk22/megalodon#940]
**Describe the bug**
In my timezone we're currently in standard time. When I use the datetime picker to schedule a post and select a datetime **before** DST starts, then the selected datetime will show the exact date and time I picked. When I pick a datetime that is **after** the moment where DST starts, then the selected datetime that is shown will be incremented by one hour.

It seems that the datetime shown to the user is corrected relative to their current timezone. It might make more sense for a user to show the absolute datetime that was picked instead of performing the correction.

E.g. When currently in standard time and picking 02:00 any date during DST, the label should display 02:00 instead of 03:00.

**To reproduce**
_see description_

**Does this happen in the official app?**
No\*

\*I don't use the official app usually, couldn't find a post schedule feature so quickly, I think it's specific to this fork. Feel free to link to or create an upstream issue if I'm wrong.

**Screenshots and screen recordings**
![Screenshot_20231123-015431](https://github.com/sk22/megalodon/assets/8693699/93737466-22b1-48d3-a562-142ef35744f0)

**Version**
Megalodon version: v2.1.6+fork.110

**Crash log**
Not applicable

**Comment by sk22** [comment]
seems the issue was actually with the date/time picker, not with the date that's shown. thanks for letting me know about this!
