### ISSUE TITLE
Move other timelines, lists, and other pages to a drawer

### ISSUE THREAD

**Issue by egel557** [sk22/megalodon#98]
I think the app really needs a drawer for easy access to different pages. The timelines located under the "Search" tab just isn't intuitive, in my opinion. Both Tusky and Fedilab have drawers, and I think the official app is really being held back by not having one. 

In terms of where to place the button that toggles the drawer, this might be a bit tricky since all the tabs don't share a header (a design flaw of the main app, in my opinion). A new shared header might need to be created.

**Comment by sk22** [comment]
i'm planning to move timelines, list and stuff somewhere, but a drawer is something i don't want, hence closing this issue

**Comment by sk22** [comment]
thanks for the idea tho!
